"""SoAI - Browser ARIA ref lookup helpers [backend/mcp/tools/browser/ref_lookup.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from typing import TYPE_CHECKING

from core.mcp.argument_validation import require_non_empty_string_value
from mcp.tools.browser.frame_tree import (
    build_frame_tree_signature,
    resolve_frame_by_path,
)
from mcp.tools.browser.session_access import clear_snapshot_refs
from mcp.tools.browser.snapshot_refs import normalize_ref_alias
from mcp.tools.browser.types import SnapshotRefMapping
from mcp.tools.error import MCPToolError, build_invalid_params_error, get_arg

if TYPE_CHECKING:
    from playwright.async_api import Locator, Page

    from core.types.json import JSONDict
    from mcp.tools.browser.types import ActionableRole, BrowserSessionState

__all__ = (
    "ensure_snapshot_refs_current_for_page",
    "locator_and_role_by_ref",
    "locator_by_ref",
    "optional_ref",
    "require_ref",
    "resolve_ref_mapping",
)


def require_ref(arguments: JSONDict, *, key: str = "ref") -> str:
    ref_raw = get_arg(arguments, key)
    return require_non_empty_string_value(
        ref_raw,
        build_error=build_invalid_params_error,
        type_message=f"Parameter '{key}' must be a non-empty string",
        empty_message=f"Parameter '{key}' must be a non-empty string",
    )


def optional_ref(arguments: JSONDict, *, key: str = "ref") -> str | None:
    ref_value = arguments.get(key)
    if ref_value is None:
        return None
    return require_non_empty_string_value(
        ref_value,
        build_error=build_invalid_params_error,
        type_message=f"{key} must be a non-empty string when provided",
        empty_message=f"{key} must be a non-empty string when provided",
    )


def _resolve_mapping(state: BrowserSessionState, ref: str) -> SnapshotRefMapping:
    if state.ref_page_url is None and not state.refs:
        raise MCPToolError(
            -32602,
            (
                f"Unknown ref: {ref}. No snapshot refs are available for the current page. "
                "Refs are generated by browser_snapshot and are cleared after navigation or page "
                "structure changes. Call browser_snapshot again and use the new ref."
            ),
            data={"refs_available": False},
        )
    mapping = state.refs.get(ref)
    if mapping is not None:
        return mapping
    lowercase_ref = ref.lower()
    if lowercase_ref != ref:
        mapping = state.refs.get(lowercase_ref)
        if mapping is not None:
            return mapping
    alias_ref = state.ref_aliases.get(normalize_ref_alias(ref))
    if alias_ref is not None:
        mapping = state.refs.get(alias_ref)
        if mapping is not None:
            return mapping
    raise MCPToolError(
        -32602,
        (
            f"Unknown ref: {ref}. Snapshot refs may be stale after navigation or page changes. "
            "Call browser_snapshot to refresh refs."
        ),
        data={"refs_available": bool(state.refs)},
    )


def ensure_snapshot_refs_current_for_page(state: BrowserSessionState, page: Page) -> None:
    if state.ref_page_url is None:
        return
    if state.ref_page_url == page.url:
        current_signature = build_frame_tree_signature(page)
        previous_signature = state.ref_frame_tree_signature
        if not previous_signature:
            return
        previous_items = set(previous_signature)
        current_items = set(current_signature)
        if previous_items.issubset(current_items):
            return
    clear_snapshot_refs(state)
    raise MCPToolError(
        -32602,
        "Snapshot refs are stale after page navigation or page structure changes. Call browser_snapshot again.",
        data={"refs_available": False},
    )


def resolve_ref_mapping(
    state: BrowserSessionState,
    page: Page,
    ref: str,
) -> tuple[ActionableRole, str, int, tuple[int, ...]]:
    ensure_snapshot_refs_current_for_page(state, page)
    mapping = _resolve_mapping(state, ref)
    return (mapping.role, mapping.name, mapping.nth, mapping.frame_path)


def _resolve_mapping_locator(
    state: BrowserSessionState,
    page: Page,
    mapping: SnapshotRefMapping,
) -> Locator:
    frame_path = mapping.frame_path
    frame_or_page = page if not frame_path else resolve_frame_by_path(page, frame_path)
    if frame_or_page is None:
        clear_snapshot_refs(state)
        raise MCPToolError(
            -32602,
            "Snapshot refs are stale after page navigation. Call browser_snapshot again.",
            data={"refs_available": False},
        )
    if isinstance(mapping.selector, str) and mapping.selector.strip():
        return frame_or_page.locator(mapping.selector)
    return frame_or_page.get_by_role(mapping.role, name=mapping.name, exact=True).nth(mapping.nth)


def locator_by_ref(state: BrowserSessionState, page: Page, ref: str) -> Locator:
    mapping = _resolve_mapping(state, ref)
    return _resolve_mapping_locator(state, page, mapping)


def locator_and_role_by_ref(
    state: BrowserSessionState,
    page: Page,
    ref: str,
) -> tuple[ActionableRole, Locator]:
    mapping = _resolve_mapping(state, ref)
    return (mapping.role, _resolve_mapping_locator(state, page, mapping))
