"""SoAI - Hardware history export query fragments [backend/core/hardware/hardware_history_query.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from core.hardware.constants import (
    CPU_METRIC_COLUMNS,
    GPU_METRIC_COLUMNS,
    NETWORK_INTERFACE_STAT_KEYS_WITH_SPEED,
)

__all__ = ()

HARDWARE_HISTORY_FIELDS: tuple[str, ...] = (
    "timestamp",
    "component",
    "device_id",
    "gpu_index",
    "mount",
    "device",
    "interface",
    *CPU_METRIC_COLUMNS,
    *GPU_METRIC_COLUMNS,
    "total_bytes",
    "used_bytes",
    "free_bytes",
    "disk_percent_used",
    *NETWORK_INTERFACE_STAT_KEYS_WITH_SPEED,
)

HARDWARE_HISTORY_SORT_FIELDS: tuple[str, ...] = (
    "timestamp",
    "component",
    "device_id",
    "gpu_index_sort",
    "mount_sort",
    "interface_sort",
)

HARDWARE_HISTORY_UNION_SQL = """
SELECT
    observed_at_ms AS timestamp,
    'cpu' AS component,
    device_id,
    NULL AS gpu_index,
    '' AS mount,
    '' AS device,
    '' AS interface,
    usage_percent,
    temperature_celsius,
    power_draw_watts,
    memory_percent,
    power_limit_watts,
    NULL AS utilization,
    NULL AS percent_used,
    NULL AS temperature,
    NULL AS power_draw_watts,
    NULL AS power_limit_watts,
    NULL AS core_clock_mhz,
    NULL AS mem_clock_mhz,
    NULL AS total_bytes,
    NULL AS used_bytes,
    NULL AS free_bytes,
    NULL AS disk_percent_used,
    NULL AS bytes_sent,
    NULL AS bytes_recv,
    NULL AS packets_sent,
    NULL AS packets_recv,
    NULL AS errin,
    NULL AS errout,
    NULL AS dropin,
    NULL AS dropout,
    NULL AS upload_mbps,
    NULL AS download_mbps,
    -1 AS gpu_index_sort,
    '' AS mount_sort,
    '' AS interface_sort
FROM hardware_cpu_history
UNION ALL
SELECT
    observed_at_ms AS timestamp,
    'gpu' AS component,
    device_id,
    gpu_index,
    '' AS mount,
    '' AS device,
    '' AS interface,
    NULL AS usage_percent,
    NULL AS temperature_celsius,
    NULL AS power_draw_watts,
    NULL AS memory_percent,
    NULL AS power_limit_watts,
    utilization,
    percent_used,
    temperature,
    power_draw_watts,
    power_limit_watts,
    core_clock_mhz,
    mem_clock_mhz,
    NULL AS total_bytes,
    NULL AS used_bytes,
    NULL AS free_bytes,
    NULL AS disk_percent_used,
    NULL AS bytes_sent,
    NULL AS bytes_recv,
    NULL AS packets_sent,
    NULL AS packets_recv,
    NULL AS errin,
    NULL AS errout,
    NULL AS dropin,
    NULL AS dropout,
    NULL AS upload_mbps,
    NULL AS download_mbps,
    gpu_index AS gpu_index_sort,
    '' AS mount_sort,
    '' AS interface_sort
FROM hardware_gpu_history
UNION ALL
SELECT
    observed_at_ms AS timestamp,
    'disk' AS component,
    '' AS device_id,
    NULL AS gpu_index,
    mount,
    device,
    '' AS interface,
    NULL AS usage_percent,
    NULL AS temperature_celsius,
    NULL AS power_draw_watts,
    NULL AS memory_percent,
    NULL AS power_limit_watts,
    NULL AS utilization,
    NULL AS percent_used,
    NULL AS temperature,
    NULL AS power_draw_watts,
    NULL AS power_limit_watts,
    NULL AS core_clock_mhz,
    NULL AS mem_clock_mhz,
    total_bytes,
    used_bytes,
    free_bytes,
    percent_used AS disk_percent_used,
    NULL AS bytes_sent,
    NULL AS bytes_recv,
    NULL AS packets_sent,
    NULL AS packets_recv,
    NULL AS errin,
    NULL AS errout,
    NULL AS dropin,
    NULL AS dropout,
    NULL AS upload_mbps,
    NULL AS download_mbps,
    -1 AS gpu_index_sort,
    mount AS mount_sort,
    '' AS interface_sort
FROM hardware_disk_history
UNION ALL
SELECT
    observed_at_ms AS timestamp,
    'network' AS component,
    '' AS device_id,
    NULL AS gpu_index,
    '' AS mount,
    '' AS device,
    interface,
    NULL AS usage_percent,
    NULL AS temperature_celsius,
    NULL AS power_draw_watts,
    NULL AS memory_percent,
    NULL AS power_limit_watts,
    NULL AS utilization,
    NULL AS percent_used,
    NULL AS temperature,
    NULL AS power_draw_watts,
    NULL AS power_limit_watts,
    NULL AS core_clock_mhz,
    NULL AS mem_clock_mhz,
    NULL AS total_bytes,
    NULL AS used_bytes,
    NULL AS free_bytes,
    NULL AS disk_percent_used,
    bytes_sent,
    bytes_recv,
    packets_sent,
    packets_recv,
    errin,
    errout,
    dropin,
    dropout,
    upload_mbps,
    download_mbps,
    -1 AS gpu_index_sort,
    '' AS mount_sort,
    interface AS interface_sort
FROM hardware_network_history
"""
