"""SoAI - Core platform protocols [backend/core/platform/protocols.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from collections.abc import Sequence
from contextlib import AbstractContextManager
from typing import Protocol

__all__ = (
    "PsutilDiskIOCountersProtocol",
    "PsutilIOCountersProtocol",
    "PsutilMemoryInfoProtocol",
    "PsutilOpenFileProtocol",
    "PsutilProcessProtocol",
)


class PsutilDiskIOCountersProtocol(Protocol):
    @property
    def read_bytes(self) -> int: ...

    @property
    def write_bytes(self) -> int: ...

    @property
    def read_count(self) -> int: ...

    @property
    def write_count(self) -> int: ...

    @property
    def read_time(self) -> int: ...

    @property
    def write_time(self) -> int: ...

    @property
    def busy_time(self) -> int | None: ...


class PsutilIOCountersProtocol(Protocol):
    @property
    def read_bytes(self) -> int: ...

    @property
    def write_bytes(self) -> int: ...


class PsutilMemoryInfoProtocol(Protocol):
    @property
    def rss(self) -> int: ...


class PsutilOpenFileProtocol(Protocol):
    @property
    def path(self) -> str: ...


class PsutilProcessProtocol(Protocol):
    def __init__(self, pid: int | None = None) -> None: ...

    @property
    def pid(self) -> int: ...

    def children(self, recursive: bool = False) -> Sequence[PsutilProcessProtocol]: ...

    def parents(self) -> Sequence[PsutilProcessProtocol]: ...

    def is_running(self) -> bool: ...

    def oneshot(self) -> AbstractContextManager[None]: ...

    def cmdline(self) -> Sequence[str]: ...

    def cwd(self) -> str: ...

    def exe(self) -> str: ...

    def open_files(self) -> Sequence[PsutilOpenFileProtocol]: ...

    def terminate(self) -> None: ...

    def kill(self) -> None: ...

    def send_signal(self, sig: int) -> None: ...

    def wait(self, timeout: float | None = None) -> int: ...

    def name(self) -> str: ...

    def username(self) -> str: ...

    def cpu_percent(self, interval: float | None = None) -> float: ...

    def memory_info(self) -> PsutilMemoryInfoProtocol: ...

    def num_threads(self) -> int: ...

    def create_time(self) -> float: ...

    def io_counters(self) -> PsutilIOCountersProtocol: ...
