#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0
set -euo pipefail

SOAI_LAUNCHER_SOURCE_PATH="${BASH_SOURCE[0]}"
SOAI_LAUNCHER_LINK_DEPTH=0
while [ -L "$SOAI_LAUNCHER_SOURCE_PATH" ]; do
    SOAI_LAUNCHER_LINK_DEPTH=$((SOAI_LAUNCHER_LINK_DEPTH + 1))
    if [ "$SOAI_LAUNCHER_LINK_DEPTH" -gt 40 ]; then
        echo "ERROR: SoAI launcher symbolic-link depth exceeds 40." >&2
        exit 1
    fi
    SOAI_LAUNCHER_SOURCE_DIRECTORY="$(cd -P "$(dirname "$SOAI_LAUNCHER_SOURCE_PATH")" && pwd)"
    SOAI_LAUNCHER_LINK_TARGET="$(readlink "$SOAI_LAUNCHER_SOURCE_PATH")"
    case "$SOAI_LAUNCHER_LINK_TARGET" in
        /*) SOAI_LAUNCHER_SOURCE_PATH="$SOAI_LAUNCHER_LINK_TARGET" ;;
        *) SOAI_LAUNCHER_SOURCE_PATH="${SOAI_LAUNCHER_SOURCE_DIRECTORY}/${SOAI_LAUNCHER_LINK_TARGET}" ;;
    esac
done
SOAI_EXPLICIT_ROOT="$(cd -P "$(dirname "$SOAI_LAUNCHER_SOURCE_PATH")" && pwd)"
cd "$SOAI_EXPLICIT_ROOT"
SCRIPT_DIR="$SOAI_EXPLICIT_ROOT"
SOAI_EXPLICIT_LAUNCHER_RELATIVE_PATH="soai.sh"
source "${SCRIPT_DIR}/backend/core/bootstrap/launcher_posix/update_recovery.sh"
soai_launcher__recover_update_transactions "$@" || exit 1
SOAI_EXPLICIT_ENTRYPOINT="${SOAI_EXPLICIT_ROOT}/backend/main.py"
SOAI_EXPLICIT_PYTHONPATH="${SOAI_EXPLICIT_ROOT}/backend"
SOAI_EXPLICIT_EDITION="soai-core"
SOAI_EXPLICIT_PRODUCT_VERSION="$(<"${SOAI_EXPLICIT_ROOT}/VERSION")"
SOAI_EXPLICIT_CORE_VERSION="$SOAI_EXPLICIT_PRODUCT_VERSION"
SOAI_EXPLICIT_ENTRYPOINT_RELATIVE_PATH="backend/main.py"
SOAI_EXPLICIT_EDITION_ROOT_ENTRIES=""
SOAI_EXPLICIT_SYSTEMD_MANAGED_MARKER=""
source "${SOAI_EXPLICIT_ROOT}/backend/core/bootstrap/launcher_posix/driver.sh"
