/* SoAI - MCP conversation settings action identifiers [frontend/assets/ts/features/chat/conversationsettings/mcpconversationsettingscontroller/actionIds.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';

const MCP_CONVERSATION_ACTION_AUTO_TOGGLE = 'chat.mcp.autoToggle';
const MCP_CONVERSATION_ACTION_SERVER_TOGGLE = 'chat.mcp.serverToggle';
const MCP_CONVERSATION_ACTION_TOOL_TOGGLE = 'chat.mcp.toolToggle';
const MCP_CONVERSATION_ACTION_TOOL_MODE_SELECT = 'chat.mcp.toolModeSelect';
const MCP_CONVERSATION_ACTION_OPEN_DEFAULT_TOOLS = 'chat.mcp.openDefaultTools';
const MCP_CONVERSATION_ACTION_DEFAULT_TOOL_TOGGLE = 'chat.mcp.defaultToolToggle';
const MCP_CONVERSATION_ACTION_RESET_TOOL_MODE_DEFAULTS = 'chat.mcp.resetToolModeDefaults';
const MCP_CONVERSATION_ACTION_TOOL_GROUP_TOGGLE = 'chat.mcp.toolGroupToggle';
const MCP_CONVERSATION_ACTION_TOOL_SEARCH = 'chat.mcp.toolSearch';

type McpConversationActionId = typeof MCP_CONVERSATION_ACTION_AUTO_TOGGLE | typeof MCP_CONVERSATION_ACTION_SERVER_TOGGLE | typeof MCP_CONVERSATION_ACTION_TOOL_TOGGLE | typeof MCP_CONVERSATION_ACTION_TOOL_MODE_SELECT | typeof MCP_CONVERSATION_ACTION_OPEN_DEFAULT_TOOLS | typeof MCP_CONVERSATION_ACTION_DEFAULT_TOOL_TOGGLE | typeof MCP_CONVERSATION_ACTION_RESET_TOOL_MODE_DEFAULTS | typeof MCP_CONVERSATION_ACTION_TOOL_GROUP_TOGGLE | typeof MCP_CONVERSATION_ACTION_TOOL_SEARCH;

const { guard: isMcpConversationClickActionId } = createActionIdSet(MCP_CONVERSATION_ACTION_TOOL_MODE_SELECT, MCP_CONVERSATION_ACTION_OPEN_DEFAULT_TOOLS, MCP_CONVERSATION_ACTION_RESET_TOOL_MODE_DEFAULTS, MCP_CONVERSATION_ACTION_TOOL_GROUP_TOGGLE);
const { guard: isMcpConversationChangeActionId } = createActionIdSet(MCP_CONVERSATION_ACTION_AUTO_TOGGLE, MCP_CONVERSATION_ACTION_SERVER_TOGGLE, MCP_CONVERSATION_ACTION_TOOL_TOGGLE, MCP_CONVERSATION_ACTION_DEFAULT_TOOL_TOGGLE);
const { guard: isMcpConversationInputActionId } = createActionIdSet(MCP_CONVERSATION_ACTION_TOOL_SEARCH);
const { guard: isMcpConversationActionId } = createActionIdSet<McpConversationActionId>(MCP_CONVERSATION_ACTION_AUTO_TOGGLE, MCP_CONVERSATION_ACTION_SERVER_TOGGLE, MCP_CONVERSATION_ACTION_TOOL_TOGGLE, MCP_CONVERSATION_ACTION_TOOL_MODE_SELECT, MCP_CONVERSATION_ACTION_OPEN_DEFAULT_TOOLS, MCP_CONVERSATION_ACTION_DEFAULT_TOOL_TOGGLE, MCP_CONVERSATION_ACTION_RESET_TOOL_MODE_DEFAULTS, MCP_CONVERSATION_ACTION_TOOL_GROUP_TOGGLE, MCP_CONVERSATION_ACTION_TOOL_SEARCH);

export { MCP_CONVERSATION_ACTION_AUTO_TOGGLE, MCP_CONVERSATION_ACTION_DEFAULT_TOOL_TOGGLE, MCP_CONVERSATION_ACTION_OPEN_DEFAULT_TOOLS, MCP_CONVERSATION_ACTION_RESET_TOOL_MODE_DEFAULTS, MCP_CONVERSATION_ACTION_SERVER_TOGGLE, MCP_CONVERSATION_ACTION_TOOL_GROUP_TOGGLE, MCP_CONVERSATION_ACTION_TOOL_MODE_SELECT, MCP_CONVERSATION_ACTION_TOOL_SEARCH, MCP_CONVERSATION_ACTION_TOOL_TOGGLE, isMcpConversationActionId, isMcpConversationChangeActionId, isMcpConversationClickActionId, isMcpConversationInputActionId };
export type { McpConversationActionId };
