"""SoAI - Shared agent and subagent status values [backend/core/agent/status_values.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = (
    "AGENT_TURN_ALL_STATUSES",
    "AGENT_TURN_STATUS_ABANDONED",
    "AGENT_TURN_STATUS_CANCELLED",
    "AGENT_TURN_STATUS_COMPLETED",
    "AGENT_TURN_STATUS_ERROR",
    "AGENT_TURN_STATUS_MAX_ITERATIONS",
    "AGENT_TURN_STATUS_RUNNING",
    "AGENT_TURN_TERMINAL_STATUSES",
    "SUBAGENT_ACKNOWLEDGEMENT_STATUSES",
    "SUBAGENT_PERSISTED_STATUSES",
    "SUBAGENT_STATUS_ABANDONED",
    "SUBAGENT_STATUS_ACCEPTED",
    "SUBAGENT_STATUS_CANCELLED",
    "SUBAGENT_STATUS_COMPLETED",
    "SUBAGENT_STATUS_ERROR",
    "SUBAGENT_STATUS_MAX_ITERATIONS",
    "SUBAGENT_STATUS_RUNNING",
    "SUBAGENT_TERMINAL_STATUSES",
)

AGENT_TURN_STATUS_RUNNING = "running"
AGENT_TURN_STATUS_COMPLETED = "completed"
AGENT_TURN_STATUS_MAX_ITERATIONS = "max_iterations"
AGENT_TURN_STATUS_CANCELLED = "cancelled"
AGENT_TURN_STATUS_ERROR = "error"
AGENT_TURN_STATUS_ABANDONED = "abandoned"

AGENT_TURN_TERMINAL_STATUSES: tuple[str, ...] = (
    AGENT_TURN_STATUS_COMPLETED,
    AGENT_TURN_STATUS_MAX_ITERATIONS,
    AGENT_TURN_STATUS_CANCELLED,
    AGENT_TURN_STATUS_ERROR,
    AGENT_TURN_STATUS_ABANDONED,
)
AGENT_TURN_ALL_STATUSES: tuple[str, ...] = (
    AGENT_TURN_STATUS_RUNNING,
    *AGENT_TURN_TERMINAL_STATUSES,
)

SUBAGENT_STATUS_ACCEPTED = "accepted"
SUBAGENT_STATUS_RUNNING = AGENT_TURN_STATUS_RUNNING
SUBAGENT_STATUS_COMPLETED = AGENT_TURN_STATUS_COMPLETED
SUBAGENT_STATUS_MAX_ITERATIONS = AGENT_TURN_STATUS_MAX_ITERATIONS
SUBAGENT_STATUS_CANCELLED = AGENT_TURN_STATUS_CANCELLED
SUBAGENT_STATUS_ERROR = AGENT_TURN_STATUS_ERROR
SUBAGENT_STATUS_ABANDONED = AGENT_TURN_STATUS_ABANDONED

SUBAGENT_TERMINAL_STATUSES: tuple[str, ...] = (
    SUBAGENT_STATUS_COMPLETED,
    SUBAGENT_STATUS_MAX_ITERATIONS,
    SUBAGENT_STATUS_CANCELLED,
    SUBAGENT_STATUS_ERROR,
    SUBAGENT_STATUS_ABANDONED,
)
SUBAGENT_PERSISTED_STATUSES: tuple[str, ...] = (
    SUBAGENT_STATUS_RUNNING,
    *SUBAGENT_TERMINAL_STATUSES,
)
SUBAGENT_ACKNOWLEDGEMENT_STATUSES: tuple[str, ...] = (SUBAGENT_STATUS_ACCEPTED,)
