/* SoAI - Hardware page actions [frontend/assets/ts/pages/hardware/actions.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';
import { HARDWARE_SOAIBENCH_HISTORY_COPY_ACTION, HARDWARE_SOAIBENCH_HISTORY_DOWNLOAD_ACTION, HARDWARE_SOAIBENCH_HISTORY_ROW_COPY_ACTION, HARDWARE_SOAIBENCH_HISTORY_ROW_DOWNLOAD_ACTION, HARDWARE_SOAIBENCH_HISTORY_SORT_ACTION } from '@features/hardware/public.ts';

const HARDWARE_ACTION_LOGS = 'hardware.logs';
const HARDWARE_ACTION_EXPORT = 'hardware.export';
const HARDWARE_ACTION_SYSTEM_INFO_OPEN = 'hardware.systemInfo.open';
const HARDWARE_ACTION_SYSTEM_INFO_COPY = 'hardware.systemInfo.copy';
const HARDWARE_ACTION_SYSTEM_INFO_DOWNLOAD = 'hardware.systemInfo.download';
const HARDWARE_ACTION_SYSTEM_INFO_ANONYMIZE = 'hardware.systemInfo.anonymize';
const HARDWARE_ACTION_PROCESS_SORT = 'hardware.process.sort';
const HARDWARE_ACTION_PROCESS_KILL = 'hardware.process.kill';
const HARDWARE_ACTION_DEVICE_SELECT = 'hardware.device.select';
const HARDWARE_ACTION_MEMORY_SWAP_TOGGLE = 'hardware.memorySwap.toggle';

const HARDWARE_ACTION_GPU_APPLY = 'hardware.gpu.apply';
const HARDWARE_ACTION_GPU_SOAIBENCH_STANDARD = 'hardware.gpu.soaibench.standard';
const HARDWARE_ACTION_GPU_SOAIBENCH_STRESS = 'hardware.gpu.soaibench.stress';
const HARDWARE_ACTION_GPU_SOAIBENCH_STOP = 'hardware.gpu.soaibench.stop';
const HARDWARE_ACTION_GPU_SOAIBENCH_HISTORY = 'hardware.gpu.soaibench.history';
const HARDWARE_ACTION_GPU_SOAIBENCH_REOPEN = 'hardware.gpu.soaibench.reopen';
const HARDWARE_ACTION_GPU_SOAIBENCH_RUN_COPY = 'hardware.gpu.soaibench.run.copy';
const HARDWARE_ACTION_GPU_SOAIBENCH_RUN_DOWNLOAD = 'hardware.gpu.soaibench.run.download';
const HARDWARE_ACTION_GPU_SOAIBENCH_START_CONFIRM = 'hardware.gpu.soaibench.start.confirm';
const HARDWARE_ACTION_GPU_SOAIBENCH_TOGGLE = 'hardware.gpu.soaibench.toggle';
const HARDWARE_ACTION_GPU_RESET = 'hardware.gpu.reset';
const HARDWARE_ACTION_GPU_SAVE_MODE = 'hardware.gpu.saveMode';
const HARDWARE_ACTION_GPU_SLOT = 'hardware.gpu.slot';
const HARDWARE_ACTION_GPU_SLIDER_INPUT = 'hardware.gpu.slider.input';
const HARDWARE_ACTION_GPU_SLIDER_AUTO = 'hardware.gpu.slider.auto';
const HARDWARE_ACTION_GPU_BOOT_TOGGLE = 'hardware.gpu.boot.toggle';

export type HardwareActionId =
    | typeof HARDWARE_ACTION_LOGS
    | typeof HARDWARE_ACTION_EXPORT
    | typeof HARDWARE_ACTION_SYSTEM_INFO_OPEN
    | typeof HARDWARE_ACTION_SYSTEM_INFO_COPY
    | typeof HARDWARE_ACTION_SYSTEM_INFO_DOWNLOAD
    | typeof HARDWARE_ACTION_SYSTEM_INFO_ANONYMIZE
    | typeof HARDWARE_ACTION_PROCESS_SORT
    | typeof HARDWARE_ACTION_PROCESS_KILL
    | typeof HARDWARE_ACTION_DEVICE_SELECT
    | typeof HARDWARE_ACTION_MEMORY_SWAP_TOGGLE
    | typeof HARDWARE_ACTION_GPU_APPLY
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_STANDARD
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_STRESS
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_STOP
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_HISTORY
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_REOPEN
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_RUN_COPY
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_RUN_DOWNLOAD
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_START_CONFIRM
    | typeof HARDWARE_ACTION_GPU_SOAIBENCH_TOGGLE
    | typeof HARDWARE_ACTION_GPU_RESET
    | typeof HARDWARE_ACTION_GPU_SAVE_MODE
    | typeof HARDWARE_ACTION_GPU_SLOT
    | typeof HARDWARE_ACTION_GPU_SLIDER_INPUT
    | typeof HARDWARE_ACTION_GPU_SLIDER_AUTO
    | typeof HARDWARE_ACTION_GPU_BOOT_TOGGLE
    | typeof HARDWARE_SOAIBENCH_HISTORY_COPY_ACTION
    | typeof HARDWARE_SOAIBENCH_HISTORY_DOWNLOAD_ACTION
    | typeof HARDWARE_SOAIBENCH_HISTORY_ROW_COPY_ACTION
    | typeof HARDWARE_SOAIBENCH_HISTORY_ROW_DOWNLOAD_ACTION
    | typeof HARDWARE_SOAIBENCH_HISTORY_SORT_ACTION;

const { guard: isHardwareActionId } = createActionIdSet(
    HARDWARE_ACTION_LOGS,
    HARDWARE_ACTION_EXPORT,
    HARDWARE_ACTION_SYSTEM_INFO_OPEN,
    HARDWARE_ACTION_SYSTEM_INFO_COPY,
    HARDWARE_ACTION_SYSTEM_INFO_DOWNLOAD,
    HARDWARE_ACTION_SYSTEM_INFO_ANONYMIZE,
    HARDWARE_ACTION_PROCESS_SORT,
    HARDWARE_ACTION_PROCESS_KILL,
    HARDWARE_ACTION_DEVICE_SELECT,
    HARDWARE_ACTION_MEMORY_SWAP_TOGGLE,
    HARDWARE_ACTION_GPU_APPLY,
    HARDWARE_ACTION_GPU_SOAIBENCH_STANDARD,
    HARDWARE_ACTION_GPU_SOAIBENCH_STRESS,
    HARDWARE_ACTION_GPU_SOAIBENCH_STOP,
    HARDWARE_ACTION_GPU_SOAIBENCH_HISTORY,
    HARDWARE_ACTION_GPU_SOAIBENCH_REOPEN,
    HARDWARE_ACTION_GPU_SOAIBENCH_RUN_COPY,
    HARDWARE_ACTION_GPU_SOAIBENCH_RUN_DOWNLOAD,
    HARDWARE_ACTION_GPU_SOAIBENCH_START_CONFIRM,
    HARDWARE_ACTION_GPU_SOAIBENCH_TOGGLE,
    HARDWARE_ACTION_GPU_RESET,
    HARDWARE_ACTION_GPU_SAVE_MODE,
    HARDWARE_ACTION_GPU_SLOT,
    HARDWARE_ACTION_GPU_SLIDER_INPUT,
    HARDWARE_ACTION_GPU_SLIDER_AUTO,
    HARDWARE_ACTION_GPU_BOOT_TOGGLE,
    HARDWARE_SOAIBENCH_HISTORY_COPY_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_DOWNLOAD_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_ROW_COPY_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_ROW_DOWNLOAD_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_SORT_ACTION
);

export {
    HARDWARE_ACTION_DEVICE_SELECT,
    HARDWARE_ACTION_EXPORT,
    HARDWARE_ACTION_GPU_APPLY,
    HARDWARE_ACTION_GPU_BOOT_TOGGLE,
    HARDWARE_ACTION_GPU_RESET,
    HARDWARE_ACTION_GPU_SAVE_MODE,
    HARDWARE_ACTION_GPU_SLIDER_AUTO,
    HARDWARE_ACTION_GPU_SLIDER_INPUT,
    HARDWARE_ACTION_GPU_SLOT,
    HARDWARE_ACTION_GPU_SOAIBENCH_HISTORY,
    HARDWARE_ACTION_GPU_SOAIBENCH_REOPEN,
    HARDWARE_ACTION_GPU_SOAIBENCH_RUN_COPY,
    HARDWARE_ACTION_GPU_SOAIBENCH_RUN_DOWNLOAD,
    HARDWARE_ACTION_GPU_SOAIBENCH_STANDARD,
    HARDWARE_ACTION_GPU_SOAIBENCH_START_CONFIRM,
    HARDWARE_ACTION_GPU_SOAIBENCH_STOP,
    HARDWARE_ACTION_GPU_SOAIBENCH_STRESS,
    HARDWARE_ACTION_GPU_SOAIBENCH_TOGGLE,
    HARDWARE_ACTION_LOGS,
    HARDWARE_ACTION_MEMORY_SWAP_TOGGLE,
    HARDWARE_ACTION_PROCESS_KILL,
    HARDWARE_ACTION_PROCESS_SORT,
    HARDWARE_ACTION_SYSTEM_INFO_ANONYMIZE,
    HARDWARE_ACTION_SYSTEM_INFO_COPY,
    HARDWARE_ACTION_SYSTEM_INFO_DOWNLOAD,
    HARDWARE_ACTION_SYSTEM_INFO_OPEN,
    HARDWARE_SOAIBENCH_HISTORY_COPY_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_DOWNLOAD_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_ROW_COPY_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_ROW_DOWNLOAD_ACTION,
    HARDWARE_SOAIBENCH_HISTORY_SORT_ACTION
};

export { isHardwareActionId };
