"""SoAI - Orchestrator metric tuple paths [backend/core/metrics/keyspace_paths_orchestrator.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from core.metrics.keyspace_base import (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_KEY_DOUBLE_FINALIZATION_COUNT,
    METRIC_KEY_EXECUTION,
    METRIC_KEY_INVARIANT_VIOLATION_COUNT,
    METRIC_KEY_INVARIANTS,
    METRIC_KEY_OPEN_CYCLES,
    METRIC_KEY_PLUGIN_ACTIVE_DELTA,
    METRIC_KEY_PROMPT_SLOT_HELD_DELTA,
    METRIC_KEY_QUEUE,
    METRIC_KEY_RETRIES_BY_EXCEPTION,
    METRIC_KEY_RETRIES_BY_PLUGIN,
    METRIC_KEY_RETRIES_TOTAL,
    METRIC_METRIC_GAUGES,
)

__all__ = ()

ORCHESTRATOR_COUNTER_QUEUE_DOUBLE_FINALIZATION: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_KEY_QUEUE,
    METRIC_KEY_DOUBLE_FINALIZATION_COUNT,
)

ORCHESTRATOR_COUNTER_INVARIANT_VIOLATION: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_KEY_INVARIANTS,
    METRIC_KEY_INVARIANT_VIOLATION_COUNT,
)

ORCHESTRATOR_GAUGE_INVARIANT_PROMPT_SLOT_DELTA: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_METRIC_GAUGES,
    METRIC_KEY_INVARIANTS,
    METRIC_KEY_PROMPT_SLOT_HELD_DELTA,
)

ORCHESTRATOR_GAUGE_INVARIANT_PLUGIN_ACTIVE_DELTA: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_METRIC_GAUGES,
    METRIC_KEY_INVARIANTS,
    METRIC_KEY_PLUGIN_ACTIVE_DELTA,
)

ORCHESTRATOR_GAUGE_OPEN_QUEUE_CYCLES: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_METRIC_GAUGES,
    METRIC_KEY_QUEUE,
    METRIC_KEY_OPEN_CYCLES,
)

ORCHESTRATOR_COUNTER_EXECUTION_RETRIES_TOTAL: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_KEY_EXECUTION,
    METRIC_KEY_RETRIES_TOTAL,
)

ORCHESTRATOR_COUNTER_EXECUTION_RETRIES_BY_PLUGIN: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_KEY_EXECUTION,
    METRIC_KEY_RETRIES_BY_PLUGIN,
)

ORCHESTRATOR_COUNTER_EXECUTION_RETRIES_BY_EXCEPTION: tuple[str, ...] = (
    METRIC_BLOCK_ORCHESTRATOR,
    METRIC_KEY_EXECUTION,
    METRIC_KEY_RETRIES_BY_EXCEPTION,
)
