"""SoAI - MCP RAG metric tuple paths [backend/core/metrics/keyspace_paths_mcp_rag.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from core.metrics.keyspace_base import (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_CHUNKING,
    METRIC_KEY_CHUNKS_CREATED,
    METRIC_KEY_DEDUPLICATED,
    METRIC_KEY_DELETIONS,
    METRIC_KEY_DOCUMENT_PROCESSING_MS,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_EMBEDDING_LATENCY_MS,
    METRIC_KEY_EMBEDDINGS,
    METRIC_KEY_FAILED,
    METRIC_KEY_HYBRID,
    METRIC_KEY_MMR,
    METRIC_KEY_PROCESSING_QUEUE_SIZE,
    METRIC_KEY_REQUESTS,
    METRIC_KEY_SEARCH_LATENCY_MS,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_SIMILARITY,
    METRIC_KEY_TOTAL,
    METRIC_KEY_UPLOADS_COMPLETED,
    METRIC_KEY_UPLOADS_FAILED,
    METRIC_KEY_UPLOADS_QUEUED,
    METRIC_KEY_WEB_FETCH_INGESTS_COMPLETED,
    METRIC_KEY_WEB_FETCH_INGESTS_FAILED,
    METRIC_KEY_WEB_FETCH_INGESTS_QUEUED,
    METRIC_METRIC_GAUGES,
    METRIC_METRIC_TIMINGS,
)

__all__ = ()

MCP_RAG_COUNTER_DOCUMENTS_UPLOADS_QUEUED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_UPLOADS_QUEUED,
)
MCP_RAG_COUNTER_DOCUMENTS_WEB_FETCH_INGESTS_QUEUED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_WEB_FETCH_INGESTS_QUEUED,
)
MCP_RAG_GAUGE_PROCESSING_QUEUE_SIZE: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_METRIC_GAUGES,
    METRIC_KEY_PROCESSING_QUEUE_SIZE,
)

MCP_RAG_COUNTER_SEARCHES_TOTAL: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_TOTAL,
)
MCP_RAG_COUNTER_SEARCHES_SIMILARITY: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_SIMILARITY,
)
MCP_RAG_COUNTER_SEARCHES_MMR: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_MMR,
)
MCP_RAG_COUNTER_SEARCHES_HYBRID: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_HYBRID,
)
MCP_RAG_COUNTER_SEARCHES_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_FAILED,
)
MCP_RAG_TIMING_SEARCH_LATENCY_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_SEARCH_LATENCY_MS,
)
MCP_RAG_TIMING_EMBEDDING_LATENCY_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_EMBEDDING_LATENCY_MS,
)
MCP_RAG_COUNTER_CHUNKING_CHUNKS_CREATED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_CHUNKING,
    METRIC_KEY_CHUNKS_CREATED,
)
MCP_RAG_COUNTER_EMBEDDINGS_REQUESTS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_EMBEDDINGS,
    METRIC_KEY_REQUESTS,
)
MCP_RAG_COUNTER_EMBEDDINGS_DEDUPLICATED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_EMBEDDINGS,
    METRIC_KEY_DEDUPLICATED,
)
MCP_RAG_COUNTER_DOCUMENTS_DELETIONS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_DELETIONS,
)
MCP_RAG_COUNTER_DOCUMENTS_UPLOADS_COMPLETED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_UPLOADS_COMPLETED,
)
MCP_RAG_COUNTER_DOCUMENTS_UPLOADS_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_UPLOADS_FAILED,
)
MCP_RAG_COUNTER_DOCUMENTS_WEB_FETCH_INGESTS_COMPLETED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_WEB_FETCH_INGESTS_COMPLETED,
)
MCP_RAG_COUNTER_DOCUMENTS_WEB_FETCH_INGESTS_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_KEY_DOCUMENTS,
    METRIC_KEY_WEB_FETCH_INGESTS_FAILED,
)
MCP_RAG_TIMING_DOCUMENT_PROCESSING_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_RAG,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_DOCUMENT_PROCESSING_MS,
)
