"""SoAI - Event bus, streaming, and WebSocket metric tuple paths [backend/core/metrics/keyspace_paths_event_streaming.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from core.metrics.keyspace_base import (
    METRIC_BLOCK_EVENT_BUS,
    METRIC_BLOCK_STREAMING,
    METRIC_BLOCK_WEBSOCKET,
    METRIC_BLOCK_WEBSOCKET_LOG_STREAM,
    METRIC_KEY_CALLBACKS,
    METRIC_KEY_CHANNEL,
    METRIC_KEY_CHUNKS,
    METRIC_KEY_COALESCED_COUNT,
    METRIC_KEY_DELIVERY,
    METRIC_KEY_DISPATCH_TIME_MS,
    METRIC_KEY_DISPATCHED_CALLBACK_COUNT,
    METRIC_KEY_DOUBLE_FINALIZATION_COUNT,
    METRIC_KEY_EVICTION_TERMINAL_COUNT,
    METRIC_KEY_FAILED_COUNT,
    METRIC_KEY_GAUGE_QUEUE_DEPTH,
    METRIC_KEY_LISTENER,
    METRIC_KEY_LOG_STREAM_DROPS,
    METRIC_KEY_QUEUE,
    METRIC_KEY_QUEUE_TIME_MS,
    METRIC_KEY_REFUSED_CANCELLATION,
    METRIC_KEY_SHUTDOWN_COUNT,
    METRIC_KEY_STALE_REMOVED_COUNT,
    METRIC_KEY_TERMINAL_FAILED_COUNT,
    METRIC_KEY_TIMEOUT_COUNT,
    METRIC_METRIC_GAUGES,
    METRIC_METRIC_TIMINGS,
)

__all__ = ()

EVENT_BUS_GAUGE_QUEUE_DEPTH: tuple[str, ...] = (
    METRIC_BLOCK_EVENT_BUS,
    METRIC_METRIC_GAUGES,
    METRIC_KEY_GAUGE_QUEUE_DEPTH,
)
EVENT_BUS_GAUGE_DISPATCHED_CALLBACK_COUNT: tuple[str, ...] = (
    METRIC_BLOCK_EVENT_BUS,
    METRIC_METRIC_GAUGES,
    METRIC_KEY_DISPATCHED_CALLBACK_COUNT,
)
EVENT_BUS_TIMING_DISPATCH_TIME_MS: tuple[str, ...] = (
    METRIC_BLOCK_EVENT_BUS,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_DISPATCH_TIME_MS,
)
EVENT_BUS_TIMING_QUEUE_TIME_MS: tuple[str, ...] = (
    METRIC_BLOCK_EVENT_BUS,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_QUEUE_TIME_MS,
)
EVENT_BUS_COUNTER_CALLBACKS_REFUSED_CANCELLATION: tuple[str, ...] = (
    METRIC_BLOCK_EVENT_BUS,
    METRIC_KEY_CALLBACKS,
    METRIC_KEY_REFUSED_CANCELLATION,
)
STREAMING_COUNTER_CHUNKS_COALESCED: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_CHUNKS,
    METRIC_KEY_COALESCED_COUNT,
)
STREAMING_COUNTER_CHANNEL_EVICTION_TERMINAL: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_CHANNEL,
    METRIC_KEY_EVICTION_TERMINAL_COUNT,
)
STREAMING_COUNTER_DELIVERY_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_DELIVERY,
    METRIC_KEY_FAILED_COUNT,
)
STREAMING_COUNTER_DELIVERY_SHUTDOWN: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_DELIVERY,
    METRIC_KEY_SHUTDOWN_COUNT,
)
STREAMING_COUNTER_DELIVERY_TIMEOUT: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_DELIVERY,
    METRIC_KEY_TIMEOUT_COUNT,
)
STREAMING_COUNTER_LISTENER_STALE_REMOVED: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_LISTENER,
    METRIC_KEY_STALE_REMOVED_COUNT,
)
STREAMING_COUNTER_TERMINAL_DELIVERY_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_DELIVERY,
    METRIC_KEY_TERMINAL_FAILED_COUNT,
)
STREAMING_COUNTER_QUEUE_DOUBLE_FINALIZATION: tuple[str, ...] = (
    METRIC_BLOCK_STREAMING,
    METRIC_KEY_QUEUE,
    METRIC_KEY_DOUBLE_FINALIZATION_COUNT,
)

WEBSOCKET_GAUGE_QUEUE_DEPTH: tuple[str, ...] = (
    METRIC_BLOCK_WEBSOCKET,
    METRIC_METRIC_GAUGES,
    METRIC_KEY_GAUGE_QUEUE_DEPTH,
)
WEBSOCKET_COUNTER_LOG_STREAM_DROPS: tuple[str, ...] = (
    METRIC_BLOCK_WEBSOCKET,
    METRIC_BLOCK_WEBSOCKET_LOG_STREAM,
    METRIC_KEY_LOG_STREAM_DROPS,
)
