"""SoAI - MCP search metric tuple paths [backend/core/metrics/keyspace_paths_mcp_search.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from core.metrics.keyspace_base import (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_BY_PROVIDER,
    METRIC_KEY_FAILED,
    METRIC_KEY_FETCH_LATENCY_MS,
    METRIC_KEY_FETCHES,
    METRIC_KEY_SEARCH_LATENCY_MS,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_SUCCEEDED,
    METRIC_KEY_TOTAL,
    METRIC_METRIC_TIMINGS,
)

__all__ = ()

MCP_SEARCH_COUNTER_SEARCHES_TOTAL: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_TOTAL,
)
MCP_SEARCH_COUNTER_SEARCHES_BY_PROVIDER: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_BY_PROVIDER,
)
MCP_SEARCH_COUNTER_SEARCHES_SUCCEEDED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_SUCCEEDED,
)
MCP_SEARCH_COUNTER_SEARCHES_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_SEARCHES,
    METRIC_KEY_FAILED,
)
MCP_SEARCH_TIMING_SEARCH_LATENCY_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_SEARCH_LATENCY_MS,
)
MCP_SEARCH_COUNTER_FETCHES_TOTAL: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_FETCHES,
    METRIC_KEY_TOTAL,
)
MCP_SEARCH_COUNTER_FETCHES_SUCCEEDED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_FETCHES,
    METRIC_KEY_SUCCEEDED,
)
MCP_SEARCH_COUNTER_FETCHES_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_KEY_FETCHES,
    METRIC_KEY_FAILED,
)
MCP_SEARCH_TIMING_FETCH_LATENCY_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SEARCH,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_FETCH_LATENCY_MS,
)
