"""SoAI - MCP server metric tuple paths [backend/core/metrics/keyspace_paths_mcp_server.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from core.metrics.keyspace_base import (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_CALLS,
    METRIC_KEY_CALLS_TOTAL,
    METRIC_KEY_CANCELLED,
    METRIC_KEY_COMPLETED,
    METRIC_KEY_CREATED,
    METRIC_KEY_DROPPED,
    METRIC_KEY_FAILED,
    METRIC_KEY_FAILURES,
    METRIC_KEY_HANDLED,
    METRIC_KEY_NOTIFICATIONS,
    METRIC_KEY_READS,
    METRIC_KEY_REQUESTS,
    METRIC_KEY_REQUESTS_LATENCY_MS,
    METRIC_KEY_RESOURCE_READ_MS,
    METRIC_KEY_RESOURCES,
    METRIC_KEY_SENT,
    METRIC_KEY_SUBSCRIPTIONS,
    METRIC_KEY_SUCCEEDED,
    METRIC_KEY_TASKS,
    METRIC_KEY_TOOL_EXECUTION_MS,
    METRIC_KEY_TOOLS,
    METRIC_KEY_TOTAL,
    METRIC_KEY_UNSUBSCRIPTIONS,
    METRIC_METRIC_TIMINGS,
)

__all__ = ()

MCP_SERVER_COUNTER_NOTIFICATIONS_DROPPED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_NOTIFICATIONS,
    METRIC_KEY_DROPPED,
)
MCP_SERVER_COUNTER_NOTIFICATIONS_SENT: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_NOTIFICATIONS,
    METRIC_KEY_SENT,
)
MCP_SERVER_COUNTER_NOTIFICATIONS_FAILURES: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_NOTIFICATIONS,
    METRIC_KEY_FAILURES,
)

MCP_SERVER_COUNTER_REQUESTS_TOTAL: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_REQUESTS,
    METRIC_KEY_TOTAL,
)
MCP_SERVER_COUNTER_REQUESTS_HANDLED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_REQUESTS,
    METRIC_KEY_HANDLED,
)
MCP_SERVER_COUNTER_REQUESTS_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_REQUESTS,
    METRIC_KEY_FAILED,
)
MCP_SERVER_TIMING_REQUEST_LATENCY_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_REQUESTS_LATENCY_MS,
)
MCP_SERVER_TIMING_RESOURCE_READ_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_RESOURCE_READ_MS,
)
MCP_SERVER_TIMING_TOOL_EXECUTION_MS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_METRIC_TIMINGS,
    METRIC_KEY_TOOL_EXECUTION_MS,
)

MCP_SERVER_COUNTER_TOOLS_CALLS_TOTAL: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_TOOLS,
    METRIC_KEY_CALLS_TOTAL,
)
MCP_SERVER_COUNTER_TOOLS_CALLS_SUCCEEDED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_TOOLS,
    METRIC_KEY_CALLS,
    METRIC_KEY_SUCCEEDED,
)
MCP_SERVER_COUNTER_TOOLS_CALLS_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_TOOLS,
    METRIC_KEY_CALLS,
    METRIC_KEY_FAILED,
)

MCP_SERVER_COUNTER_TASKS_CREATED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_TASKS,
    METRIC_KEY_CREATED,
)
MCP_SERVER_COUNTER_TASKS_COMPLETED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_TASKS,
    METRIC_KEY_COMPLETED,
)
MCP_SERVER_COUNTER_TASKS_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_TASKS,
    METRIC_KEY_FAILED,
)
MCP_SERVER_COUNTER_TASKS_CANCELLED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_TASKS,
    METRIC_KEY_CANCELLED,
)

MCP_SERVER_COUNTER_RESOURCES_READS_TOTAL: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_RESOURCES,
    METRIC_KEY_READS,
    METRIC_KEY_TOTAL,
)
MCP_SERVER_COUNTER_RESOURCES_READS_SUCCEEDED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_RESOURCES,
    METRIC_KEY_READS,
    METRIC_KEY_SUCCEEDED,
)
MCP_SERVER_COUNTER_RESOURCES_READS_FAILED: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_RESOURCES,
    METRIC_KEY_READS,
    METRIC_KEY_FAILED,
)
MCP_SERVER_COUNTER_RESOURCES_SUBSCRIPTIONS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_RESOURCES,
    METRIC_KEY_SUBSCRIPTIONS,
)
MCP_SERVER_COUNTER_RESOURCES_UNSUBSCRIPTIONS: tuple[str, ...] = (
    METRIC_BLOCK_MCP_SERVER,
    METRIC_KEY_RESOURCES,
    METRIC_KEY_UNSUBSCRIPTIONS,
)
