/* SoAI - Models page actions [frontend/assets/ts/pages/models/actions.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';
import { MODELS_ACTION_ADD_PROVIDER, MODELS_ACTION_DOWNLOAD_MODEL, MODELS_ACTION_MANAGE_PROVIDERS, MODELS_ACTION_MANAGE_VIRTUAL_MODELS, MODELS_ACTION_METRIC_BADGE, MODELS_ACTION_OPEN_METRICS, MODELS_ACTION_OPEN_PROVIDER_TAB } from '@core/models/pageActions.ts';

const MODELS_ACTION_DELETE = 'delete';
const MODELS_ACTION_EDIT_MODEL = 'edit-model';
const MODELS_ACTION_EDIT_VIRTUAL = 'edit-virtual';
const MODELS_ACTION_EDIT_PARAMETERS = 'edit-params';
const MODELS_ACTION_STOP_MODEL = 'stop-model';
const MODELS_ACTION_TOGGLE_ENABLED = 'toggle-model-enabled';
const MODELS_ACTION_TOGGLE_VIEW_MODE = 'models.toggleViewMode';
const MODELS_ACTION_SORT_LIST = 'models.sortList';

export type ModelsActionId = typeof MODELS_ACTION_DELETE | typeof MODELS_ACTION_EDIT_MODEL | typeof MODELS_ACTION_EDIT_VIRTUAL | typeof MODELS_ACTION_EDIT_PARAMETERS | typeof MODELS_ACTION_STOP_MODEL | typeof MODELS_ACTION_TOGGLE_ENABLED;
export type ModelsPageActionId = typeof MODELS_ACTION_ADD_PROVIDER | typeof MODELS_ACTION_DOWNLOAD_MODEL | typeof MODELS_ACTION_MANAGE_PROVIDERS | typeof MODELS_ACTION_MANAGE_VIRTUAL_MODELS | typeof MODELS_ACTION_OPEN_METRICS | typeof MODELS_ACTION_OPEN_PROVIDER_TAB | typeof MODELS_ACTION_METRIC_BADGE | typeof MODELS_ACTION_TOGGLE_VIEW_MODE | typeof MODELS_ACTION_SORT_LIST;
export type ModelsDataActionId = ModelsActionId | ModelsPageActionId;

const { guard: isModelsActionId } = createActionIdSet<ModelsActionId>(MODELS_ACTION_DELETE, MODELS_ACTION_EDIT_MODEL, MODELS_ACTION_EDIT_VIRTUAL, MODELS_ACTION_EDIT_PARAMETERS, MODELS_ACTION_STOP_MODEL, MODELS_ACTION_TOGGLE_ENABLED);
const { guard: isModelsPageActionId } = createActionIdSet<ModelsPageActionId>(MODELS_ACTION_ADD_PROVIDER, MODELS_ACTION_DOWNLOAD_MODEL, MODELS_ACTION_MANAGE_PROVIDERS, MODELS_ACTION_MANAGE_VIRTUAL_MODELS, MODELS_ACTION_OPEN_METRICS, MODELS_ACTION_OPEN_PROVIDER_TAB, MODELS_ACTION_METRIC_BADGE, MODELS_ACTION_TOGGLE_VIEW_MODE, MODELS_ACTION_SORT_LIST);

const isModelsDataActionId = (value: string | undefined): value is ModelsDataActionId => {
    return isModelsActionId(value) || isModelsPageActionId(value);
};

export { MODELS_ACTION_DELETE, MODELS_ACTION_EDIT_MODEL, MODELS_ACTION_EDIT_PARAMETERS, MODELS_ACTION_EDIT_VIRTUAL, MODELS_ACTION_SORT_LIST, MODELS_ACTION_STOP_MODEL, MODELS_ACTION_TOGGLE_ENABLED, MODELS_ACTION_TOGGLE_VIEW_MODE, isModelsActionId, isModelsDataActionId, isModelsPageActionId };
