"""SoAI - Native SoAI V1 contract constants [backend/core/meta/soai_v1_contract.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = (
    "CORE_SYSTEM_PROMPTS_CATALOG_SCHEMA_VERSION",
    "SOAI_API_V1_PREFIX",
    "SOAI_CONFIG_SCHEMA_VERSION",
    "SOAI_CONTRACT_VERSION",
    "SOAI_DATABASE_APPLICATION_ID",
    "SOAI_DATABASE_SCHEMA_VERSION",
    "SOAI_OPENAI_COMPAT_V1_PREFIX",
    "SOAI_SCHEMA_VERSION",
    "WEBUI_MEDIA_PREVIEW_CACHE_METADATA_SCHEMA_VERSION",
)

CORE_SYSTEM_PROMPTS_CATALOG_SCHEMA_VERSION: int = 1
SOAI_CONTRACT_VERSION: str = "v1"
SOAI_SCHEMA_VERSION: int = 1
SOAI_CONFIG_SCHEMA_VERSION: int = SOAI_SCHEMA_VERSION
SOAI_DATABASE_SCHEMA_VERSION: int = 2
SOAI_DATABASE_APPLICATION_ID: int = 260822
SOAI_API_V1_PREFIX: str = "/api/v1"
SOAI_OPENAI_COMPAT_V1_PREFIX: str = "/v1"
WEBUI_MEDIA_PREVIEW_CACHE_METADATA_SCHEMA_VERSION: int = 1
