/* SoAI - Automation feature actions [frontend/assets/ts/features/automation/actions.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';

export const AUTOMATION_ACTION_NAV_PREVIOUS = 'automation:nav-previous';
export const AUTOMATION_ACTION_NAV_NEXT = 'automation:nav-next';
export const AUTOMATION_ACTION_NAV_TODAY = 'automation:nav-today';
export const AUTOMATION_ACTION_SET_VIEW = 'automation:set-view';
export const AUTOMATION_ACTION_CYCLE_VIEW = 'automation:cycle-view';
export const AUTOMATION_ACTION_SELECT_DAY = 'automation:select-day';
export const AUTOMATION_ACTION_SELECT_ZONE = 'automation:select-zone';
export const AUTOMATION_ACTION_TIME_GRID_CREATE_AT = 'automation:time-grid-create-at';
export const AUTOMATION_ACTION_OPEN_CREATE_MODAL = 'automation:open-create-modal';
export const AUTOMATION_ACTION_REGISTRY_PREVIOUS = 'automation:registry-previous';
export const AUTOMATION_ACTION_REGISTRY_NEXT = 'automation:registry-next';
export const AUTOMATION_ACTION_OPEN_CALENDAR_SETTINGS_MODAL = 'automation:open-calendar-settings';
export const AUTOMATION_ACTION_TOGGLE_REGISTRY_OVERLAY = 'automation:toggle-registry-overlay';
export const AUTOMATION_ACTION_SAVE_AUTOMATION = 'automation:save-automation';
export const AUTOMATION_ACTION_SAVE_CALENDAR_SETTINGS = 'automation:save-calendar-settings';
export const AUTOMATION_ACTION_ADD_TURN = 'automation:add-turn';
export const AUTOMATION_ACTION_REMOVE_TURN = 'automation:remove-turn';
export const AUTOMATION_ACTION_TOGGLE_AUTOMATION_ENABLED = 'automation:toggle-automation-enabled';
export const AUTOMATION_ACTION_EDIT_AUTOMATION = 'automation:edit-automation';
export const AUTOMATION_ACTION_PREVIEW_AUTOMATION = 'automation:preview-automation';
export const AUTOMATION_ACTION_DELETE_AUTOMATION = 'automation:delete-automation';
export const AUTOMATION_ACTION_MODAL_EDIT = 'automation:modal-edit';
export const AUTOMATION_ACTION_OPEN_FOLDER_MODAL = 'automation:open-folder-modal';
export const AUTOMATION_ACTION_OPEN_PARAMETERS_MODAL = 'automation:open-parameters-modal';
export const AUTOMATION_ACTION_OPEN_CHAT_TRANSCRIPT = 'automation:open-chat-transcript';
export const AUTOMATION_ACTION_RESET_PREFERENCES = 'automation:reset-preferences';
export const AUTOMATION_ACTION_WINDOW_RUNS_ENTER_SELECT_MODE = 'automation:window-runs-enter-select-mode';
export const AUTOMATION_ACTION_WINDOW_RUNS_EXIT_SELECT_MODE = 'automation:window-runs-exit-select-mode';
export const AUTOMATION_ACTION_WINDOW_RUNS_TOGGLE_SELECTED = 'automation:window-runs-toggle-selected';
export const AUTOMATION_ACTION_WINDOW_RUNS_BATCH_DELETE = 'automation:window-runs-batch-delete';
export const AUTOMATION_ACTION_WINDOW_RUNS_DELETE_OCCURRENCE = 'automation:window-runs-delete-occurrence';
export const AUTOMATION_ACTION_MCP_SERVER_TOGGLE = 'automation:mcp-server-toggle';
export const AUTOMATION_ACTION_MCP_TOOL_TOGGLE = 'automation:mcp-tool-toggle';
export const AUTOMATION_ACTION_MCP_TOOL_GROUP_TOGGLE = 'automation:mcp-tool-group-toggle';
export const AUTOMATION_ACTION_MCP_TOOL_SEARCH = 'automation:mcp-tool-search';

export type AutomationActionId =
    | typeof AUTOMATION_ACTION_NAV_PREVIOUS
    | typeof AUTOMATION_ACTION_NAV_NEXT
    | typeof AUTOMATION_ACTION_NAV_TODAY
    | typeof AUTOMATION_ACTION_SET_VIEW
    | typeof AUTOMATION_ACTION_CYCLE_VIEW
    | typeof AUTOMATION_ACTION_SELECT_DAY
    | typeof AUTOMATION_ACTION_SELECT_ZONE
    | typeof AUTOMATION_ACTION_TIME_GRID_CREATE_AT
    | typeof AUTOMATION_ACTION_OPEN_CREATE_MODAL
    | typeof AUTOMATION_ACTION_REGISTRY_PREVIOUS
    | typeof AUTOMATION_ACTION_REGISTRY_NEXT
    | typeof AUTOMATION_ACTION_OPEN_CALENDAR_SETTINGS_MODAL
    | typeof AUTOMATION_ACTION_TOGGLE_REGISTRY_OVERLAY
    | typeof AUTOMATION_ACTION_SAVE_AUTOMATION
    | typeof AUTOMATION_ACTION_SAVE_CALENDAR_SETTINGS
    | typeof AUTOMATION_ACTION_ADD_TURN
    | typeof AUTOMATION_ACTION_REMOVE_TURN
    | typeof AUTOMATION_ACTION_TOGGLE_AUTOMATION_ENABLED
    | typeof AUTOMATION_ACTION_EDIT_AUTOMATION
    | typeof AUTOMATION_ACTION_PREVIEW_AUTOMATION
    | typeof AUTOMATION_ACTION_DELETE_AUTOMATION
    | typeof AUTOMATION_ACTION_MODAL_EDIT
    | typeof AUTOMATION_ACTION_OPEN_FOLDER_MODAL
    | typeof AUTOMATION_ACTION_OPEN_PARAMETERS_MODAL
    | typeof AUTOMATION_ACTION_OPEN_CHAT_TRANSCRIPT
    | typeof AUTOMATION_ACTION_RESET_PREFERENCES
    | typeof AUTOMATION_ACTION_WINDOW_RUNS_ENTER_SELECT_MODE
    | typeof AUTOMATION_ACTION_WINDOW_RUNS_EXIT_SELECT_MODE
    | typeof AUTOMATION_ACTION_WINDOW_RUNS_TOGGLE_SELECTED
    | typeof AUTOMATION_ACTION_WINDOW_RUNS_BATCH_DELETE
    | typeof AUTOMATION_ACTION_WINDOW_RUNS_DELETE_OCCURRENCE
    | typeof AUTOMATION_ACTION_MCP_SERVER_TOGGLE
    | typeof AUTOMATION_ACTION_MCP_TOOL_TOGGLE
    | typeof AUTOMATION_ACTION_MCP_TOOL_GROUP_TOGGLE
    | typeof AUTOMATION_ACTION_MCP_TOOL_SEARCH;

const { guard: isAutomationActionId } = createActionIdSet(
    AUTOMATION_ACTION_NAV_PREVIOUS,
    AUTOMATION_ACTION_NAV_NEXT,
    AUTOMATION_ACTION_NAV_TODAY,
    AUTOMATION_ACTION_SET_VIEW,
    AUTOMATION_ACTION_CYCLE_VIEW,
    AUTOMATION_ACTION_SELECT_DAY,
    AUTOMATION_ACTION_SELECT_ZONE,
    AUTOMATION_ACTION_TIME_GRID_CREATE_AT,
    AUTOMATION_ACTION_OPEN_CREATE_MODAL,
    AUTOMATION_ACTION_REGISTRY_PREVIOUS,
    AUTOMATION_ACTION_REGISTRY_NEXT,
    AUTOMATION_ACTION_OPEN_CALENDAR_SETTINGS_MODAL,
    AUTOMATION_ACTION_TOGGLE_REGISTRY_OVERLAY,
    AUTOMATION_ACTION_SAVE_AUTOMATION,
    AUTOMATION_ACTION_SAVE_CALENDAR_SETTINGS,
    AUTOMATION_ACTION_ADD_TURN,
    AUTOMATION_ACTION_REMOVE_TURN,
    AUTOMATION_ACTION_TOGGLE_AUTOMATION_ENABLED,
    AUTOMATION_ACTION_EDIT_AUTOMATION,
    AUTOMATION_ACTION_PREVIEW_AUTOMATION,
    AUTOMATION_ACTION_DELETE_AUTOMATION,
    AUTOMATION_ACTION_MODAL_EDIT,
    AUTOMATION_ACTION_OPEN_FOLDER_MODAL,
    AUTOMATION_ACTION_OPEN_PARAMETERS_MODAL,
    AUTOMATION_ACTION_OPEN_CHAT_TRANSCRIPT,
    AUTOMATION_ACTION_RESET_PREFERENCES,
    AUTOMATION_ACTION_WINDOW_RUNS_ENTER_SELECT_MODE,
    AUTOMATION_ACTION_WINDOW_RUNS_EXIT_SELECT_MODE,
    AUTOMATION_ACTION_WINDOW_RUNS_TOGGLE_SELECTED,
    AUTOMATION_ACTION_WINDOW_RUNS_BATCH_DELETE,
    AUTOMATION_ACTION_WINDOW_RUNS_DELETE_OCCURRENCE,
    AUTOMATION_ACTION_MCP_SERVER_TOGGLE,
    AUTOMATION_ACTION_MCP_TOOL_TOGGLE,
    AUTOMATION_ACTION_MCP_TOOL_GROUP_TOGGLE,
    AUTOMATION_ACTION_MCP_TOOL_SEARCH
);

export { isAutomationActionId };
