/* SoAI - Shared state plugin status [frontend/assets/ts/core/state/pluginStatus.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import type { JsonValue } from '@core/types/jsonValues.ts';
import { toTrimmedUpper } from '@core/normalize.ts';
import { isObject } from '@core/typeGuards.ts';

const PLUGIN_STATUS_UNKNOWN = 'UNKNOWN';
const PLUGIN_STATUS_STOPPED = 'STOPPED';
const PLUGIN_STATUS_DISABLED = 'DISABLED';
const PLUGIN_STATUS_INCOMPATIBLE = 'INCOMPATIBLE';
const PLUGIN_STATUS_QUARANTINED = 'QUARANTINED';
const PLUGIN_STATUS_BACKEND_NOT_INSTALLED = 'BACKEND_NOT_INSTALLED';
const PLUGIN_STATUS_BACKEND_INSTALLING = 'BACKEND_INSTALLING';
const PLUGIN_STATUS_BACKEND_UPDATING = 'BACKEND_UPDATING';
const PLUGIN_STATUS_INSTALL_ERROR = 'INSTALL_ERROR';
const PLUGIN_STATUS_LOAD_ERROR = 'LOAD_ERROR';
const PLUGIN_STATUS_UPDATE_ERROR = 'UPDATE_ERROR';
const PLUGIN_STATUS_BACKEND_UNINSTALL_ERROR = 'BACKEND_UNINSTALL_ERROR';
const PLUGIN_STATUS_DELETE_ERROR = 'DELETE_ERROR';
const PLUGIN_STATUS_PERSISTENT_READY = 'PERSISTENT_READY';

const PLUGIN_ACTIVE_STATUSES: ReadonlySet<string> = new Set(['READY', 'PROCESSING', 'STARTING', 'READY_DIRTY', 'READY_PENDING_DISPATCH', 'LOADING', PLUGIN_STATUS_BACKEND_INSTALLING, PLUGIN_STATUS_BACKEND_UPDATING, PLUGIN_STATUS_PERSISTENT_READY]);
const PLUGIN_TOGGLE_ENABLED_STATUSES: ReadonlySet<string> = new Set(['IDLE', 'LOADING', 'PROCESSING', 'READY', 'READY_DIRTY', 'READY_PENDING_DISPATCH', 'RUNNING', 'STARTING', PLUGIN_STATUS_PERSISTENT_READY]);
const PLUGIN_BLOCKING_STATUSES: ReadonlySet<string> = new Set(['STARTING', 'LOADING', 'READY_PENDING_DISPATCH', 'READY_DIRTY', 'PROCESSING']);
const PLUGIN_MODEL_UNAVAILABLE_STATUSES: ReadonlySet<string> = new Set([PLUGIN_STATUS_DISABLED, PLUGIN_STATUS_QUARANTINED, PLUGIN_STATUS_BACKEND_NOT_INSTALLED, PLUGIN_STATUS_BACKEND_INSTALLING, PLUGIN_STATUS_BACKEND_UPDATING, PLUGIN_STATUS_INSTALL_ERROR, PLUGIN_STATUS_LOAD_ERROR, PLUGIN_STATUS_UPDATE_ERROR, PLUGIN_STATUS_BACKEND_UNINSTALL_ERROR, PLUGIN_STATUS_DELETE_ERROR, PLUGIN_STATUS_INCOMPATIBLE, 'NOT_DETECTED', 'ABSENT', 'REMOVING_BACKEND', 'DELETING']);

const isPluginActiveStatus = (status: string): boolean => PLUGIN_ACTIVE_STATUSES.has(status);
const isPluginBlockingStatus = (status: string): boolean => PLUGIN_BLOCKING_STATUSES.has(status);
const isPluginModelUnavailableStatus = (status: string): boolean => PLUGIN_MODEL_UNAVAILABLE_STATUSES.has(status);
const isPluginInstallUnavailableStatus = (status: string): boolean => status === PLUGIN_STATUS_BACKEND_NOT_INSTALLED || status === PLUGIN_STATUS_BACKEND_INSTALLING || status === PLUGIN_STATUS_BACKEND_UPDATING || status === PLUGIN_STATUS_INSTALL_ERROR;

const resolvePluginStatusFromRecord = (plugin: JsonValue, normalizeStatus?: (status: JsonValue) => string): string => {
    if (!isObject(plugin)) {
        return PLUGIN_STATUS_UNKNOWN;
    }
    const raw = plugin['state'] || (plugin['isEnabled'] ? 'IDLE' : PLUGIN_STATUS_DISABLED);
    const normalized = normalizeStatus?.(raw);
    return normalized || toTrimmedUpper(String(raw)) || PLUGIN_STATUS_DISABLED;
};

export { PLUGIN_ACTIVE_STATUSES, PLUGIN_BLOCKING_STATUSES, PLUGIN_MODEL_UNAVAILABLE_STATUSES, PLUGIN_TOGGLE_ENABLED_STATUSES, PLUGIN_STATUS_BACKEND_INSTALLING, PLUGIN_STATUS_BACKEND_NOT_INSTALLED, PLUGIN_STATUS_BACKEND_UPDATING, PLUGIN_STATUS_DELETE_ERROR, PLUGIN_STATUS_DISABLED, PLUGIN_STATUS_INCOMPATIBLE, PLUGIN_STATUS_INSTALL_ERROR, PLUGIN_STATUS_LOAD_ERROR, PLUGIN_STATUS_PERSISTENT_READY, PLUGIN_STATUS_QUARANTINED, PLUGIN_STATUS_BACKEND_UNINSTALL_ERROR, PLUGIN_STATUS_STOPPED, PLUGIN_STATUS_UNKNOWN, PLUGIN_STATUS_UPDATE_ERROR, isPluginActiveStatus, isPluginBlockingStatus, isPluginInstallUnavailableStatus, isPluginModelUnavailableStatus, resolvePluginStatusFromRecord };
