/* SoAI - Models modal constants [frontend/assets/ts/features/models/modals/constants.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';

const MODELS_DOWNLOAD_MODAL_ID = 'download-model-modal';
const MODELS_EDIT_MODEL_MODAL_ID = 'edit-model-modal';
const MODELS_RENAME_MODEL_MODAL_ID = 'rename-model-modal';
const MODELS_PROVIDERS_MODAL_ID = 'providers-modal';
const MODELS_VIRTUAL_MODELS_MODAL_ID = 'virtual-models-modal';
const MODELS_VIRTUAL_MODEL_EDIT_MODAL_ID = 'vm-edit-modal';

const EDIT_MODEL_MODAL_ACTION_COPY_SOURCE = 'edit-model.copySource';
const EDIT_MODEL_MODAL_ACTION_VIEW_INFO = 'edit-model.viewInfo';
const EDIT_MODEL_MODAL_ACTION_TEST_MODEL = 'edit-model.testModel';
const EDIT_MODEL_MODAL_ACTION_EDIT_PARAMETERS = 'edit-model.editParameters';
const EDIT_MODEL_MODAL_ACTION_RENAME = 'edit-model.rename';
const EDIT_MODEL_MODAL_ACTION_DELETE = 'edit-model.delete';
const EDIT_MODEL_MODAL_ACTION_SAVE = 'edit-model.save';
const EDIT_MODEL_MODAL_ACTION_TOGGLE_ENABLED = 'toggle-model-enabled';
const EDIT_MODEL_MODAL_ACTION_TOGGLE_OPENAI_CAPABILITY = 'toggle-openai-capability';
const VIRTUAL_MODELS_MODAL_ACTION_CREATE_TAB = 'virtual-models.createTab';
const VIRTUAL_MODELS_MODAL_ACTION_LIST_TAB = 'virtual-models.listTab';
const VIRTUAL_MODELS_MODAL_ACTION_EDIT = 'virtual-models.edit';
const VIRTUAL_MODELS_MODAL_ACTION_DELETE = 'virtual-models.delete';

type EditModelModalClickActionId = typeof EDIT_MODEL_MODAL_ACTION_COPY_SOURCE | typeof EDIT_MODEL_MODAL_ACTION_VIEW_INFO | typeof EDIT_MODEL_MODAL_ACTION_TEST_MODEL | typeof EDIT_MODEL_MODAL_ACTION_EDIT_PARAMETERS | typeof EDIT_MODEL_MODAL_ACTION_RENAME | typeof EDIT_MODEL_MODAL_ACTION_DELETE | typeof EDIT_MODEL_MODAL_ACTION_SAVE;

type EditModelModalChangeActionId = typeof EDIT_MODEL_MODAL_ACTION_TOGGLE_ENABLED | typeof EDIT_MODEL_MODAL_ACTION_TOGGLE_OPENAI_CAPABILITY;

type VirtualModelsModalClickActionId = typeof VIRTUAL_MODELS_MODAL_ACTION_CREATE_TAB | typeof VIRTUAL_MODELS_MODAL_ACTION_LIST_TAB | typeof VIRTUAL_MODELS_MODAL_ACTION_EDIT | typeof VIRTUAL_MODELS_MODAL_ACTION_DELETE;

const { guard: isEditModelModalClickActionId } = createActionIdSet<EditModelModalClickActionId>(EDIT_MODEL_MODAL_ACTION_COPY_SOURCE, EDIT_MODEL_MODAL_ACTION_VIEW_INFO, EDIT_MODEL_MODAL_ACTION_TEST_MODEL, EDIT_MODEL_MODAL_ACTION_EDIT_PARAMETERS, EDIT_MODEL_MODAL_ACTION_RENAME, EDIT_MODEL_MODAL_ACTION_DELETE, EDIT_MODEL_MODAL_ACTION_SAVE);

const { guard: isEditModelModalChangeActionId } = createActionIdSet<EditModelModalChangeActionId>(EDIT_MODEL_MODAL_ACTION_TOGGLE_ENABLED, EDIT_MODEL_MODAL_ACTION_TOGGLE_OPENAI_CAPABILITY);

const { guard: isVirtualModelsModalClickActionId } = createActionIdSet<VirtualModelsModalClickActionId>(VIRTUAL_MODELS_MODAL_ACTION_CREATE_TAB, VIRTUAL_MODELS_MODAL_ACTION_LIST_TAB, VIRTUAL_MODELS_MODAL_ACTION_EDIT, VIRTUAL_MODELS_MODAL_ACTION_DELETE);

export { EDIT_MODEL_MODAL_ACTION_COPY_SOURCE, EDIT_MODEL_MODAL_ACTION_DELETE, EDIT_MODEL_MODAL_ACTION_EDIT_PARAMETERS, EDIT_MODEL_MODAL_ACTION_RENAME, EDIT_MODEL_MODAL_ACTION_SAVE, EDIT_MODEL_MODAL_ACTION_TEST_MODEL, EDIT_MODEL_MODAL_ACTION_TOGGLE_ENABLED, EDIT_MODEL_MODAL_ACTION_TOGGLE_OPENAI_CAPABILITY, EDIT_MODEL_MODAL_ACTION_VIEW_INFO, MODELS_DOWNLOAD_MODAL_ID, MODELS_EDIT_MODEL_MODAL_ID, MODELS_PROVIDERS_MODAL_ID, MODELS_RENAME_MODEL_MODAL_ID, MODELS_VIRTUAL_MODELS_MODAL_ID, MODELS_VIRTUAL_MODEL_EDIT_MODAL_ID, VIRTUAL_MODELS_MODAL_ACTION_CREATE_TAB, VIRTUAL_MODELS_MODAL_ACTION_DELETE, VIRTUAL_MODELS_MODAL_ACTION_EDIT, VIRTUAL_MODELS_MODAL_ACTION_LIST_TAB, isEditModelModalChangeActionId, isEditModelModalClickActionId, isVirtualModelsModalClickActionId };
export type { EditModelModalChangeActionId, EditModelModalClickActionId, VirtualModelsModalClickActionId };
