/* SoAI - Plugins page actions [frontend/assets/ts/pages/plugins/actions.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';
import { PLUGINS_ACTION_BACKEND_INSTALL_START, PLUGINS_ACTION_BACKEND_UNINSTALL, PLUGINS_ACTION_BACKEND_UPDATE_CHECK, PLUGINS_ACTION_CLONE_START, PLUGINS_ACTION_CONCURRENT_SAVE, PLUGINS_ACTION_CONCURRENT_SLIDER_INPUT, PLUGINS_ACTION_CONCURRENT_VALUE_INPUT, PLUGINS_ACTION_CONFIG_SAVE, PLUGINS_ACTION_DOWNLOAD_CHOOSE_FILE, PLUGINS_ACTION_DOWNLOAD_CONFIRM, PLUGINS_ACTION_DOWNLOAD_FILE_CHANGE, PLUGINS_ACTION_DOWNLOAD_FILE_TAB, PLUGINS_ACTION_DOWNLOAD_MANUAL_COPY_PATH, PLUGINS_ACTION_DOWNLOAD_MANUAL_OPEN_FILE_EXPLORER, PLUGINS_ACTION_DOWNLOAD_MANUAL_RESTART, PLUGINS_ACTION_DOWNLOAD_MANUAL_TAB, PLUGINS_ACTION_DOWNLOAD_PLUGIN, PLUGINS_ACTION_DOWNLOAD_URL_INPUT, PLUGINS_ACTION_DOWNLOAD_URL_TAB, PLUGINS_ACTION_INFO_COPY, PLUGINS_ACTION_METRIC_BADGE, PLUGINS_ACTION_OPEN_CONCURRENT, PLUGINS_ACTION_STOP_ALL, PLUGIN_ACTION_HANDLERS } from '@features/plugins/public.ts';

type PluginsCardActionId = Extract<keyof typeof PLUGIN_ACTION_HANDLERS, string>;
const PLUGINS_ACTION_TOGGLE_VIEW_MODE = 'plugins.toggleViewMode';
const PLUGINS_ACTION_SORT_LIST = 'plugins.sortList';
type PluginsPageClickActionId = typeof PLUGINS_ACTION_DOWNLOAD_PLUGIN | typeof PLUGINS_ACTION_STOP_ALL | typeof PLUGINS_ACTION_OPEN_CONCURRENT | typeof PLUGINS_ACTION_DOWNLOAD_CHOOSE_FILE | typeof PLUGINS_ACTION_DOWNLOAD_CONFIRM | typeof PLUGINS_ACTION_DOWNLOAD_URL_TAB | typeof PLUGINS_ACTION_DOWNLOAD_FILE_TAB | typeof PLUGINS_ACTION_DOWNLOAD_MANUAL_TAB | typeof PLUGINS_ACTION_DOWNLOAD_MANUAL_COPY_PATH | typeof PLUGINS_ACTION_DOWNLOAD_MANUAL_OPEN_FILE_EXPLORER | typeof PLUGINS_ACTION_DOWNLOAD_MANUAL_RESTART | typeof PLUGINS_ACTION_CONFIG_SAVE | typeof PLUGINS_ACTION_INFO_COPY | typeof PLUGINS_ACTION_BACKEND_INSTALL_START | typeof PLUGINS_ACTION_BACKEND_UPDATE_CHECK | typeof PLUGINS_ACTION_BACKEND_UNINSTALL | typeof PLUGINS_ACTION_CONCURRENT_SAVE | typeof PLUGINS_ACTION_CLONE_START | typeof PLUGINS_ACTION_TOGGLE_VIEW_MODE | typeof PLUGINS_ACTION_SORT_LIST;
type PluginsPageInputActionId = typeof PLUGINS_ACTION_DOWNLOAD_URL_INPUT | typeof PLUGINS_ACTION_CONCURRENT_SLIDER_INPUT | typeof PLUGINS_ACTION_CONCURRENT_VALUE_INPUT;
type PluginsPageChangeActionId = typeof PLUGINS_ACTION_DOWNLOAD_FILE_CHANGE;
type PluginsPageRootActionId = typeof PLUGINS_ACTION_METRIC_BADGE;
type PluginsPageActionId = PluginsPageClickActionId | PluginsPageInputActionId | PluginsPageChangeActionId | PluginsPageRootActionId;
export type PluginsActionId = PluginsCardActionId | PluginsPageActionId;

const PLUGINS_PAGE_ACTION_IDS: readonly PluginsPageActionId[] = [PLUGINS_ACTION_DOWNLOAD_PLUGIN, PLUGINS_ACTION_STOP_ALL, PLUGINS_ACTION_OPEN_CONCURRENT, PLUGINS_ACTION_TOGGLE_VIEW_MODE, PLUGINS_ACTION_SORT_LIST, PLUGINS_ACTION_METRIC_BADGE, PLUGINS_ACTION_DOWNLOAD_CHOOSE_FILE, PLUGINS_ACTION_DOWNLOAD_CONFIRM, PLUGINS_ACTION_DOWNLOAD_URL_TAB, PLUGINS_ACTION_DOWNLOAD_FILE_TAB, PLUGINS_ACTION_DOWNLOAD_MANUAL_TAB, PLUGINS_ACTION_DOWNLOAD_MANUAL_COPY_PATH, PLUGINS_ACTION_DOWNLOAD_MANUAL_OPEN_FILE_EXPLORER, PLUGINS_ACTION_DOWNLOAD_MANUAL_RESTART, PLUGINS_ACTION_CONFIG_SAVE, PLUGINS_ACTION_INFO_COPY, PLUGINS_ACTION_BACKEND_INSTALL_START, PLUGINS_ACTION_BACKEND_UPDATE_CHECK, PLUGINS_ACTION_BACKEND_UNINSTALL, PLUGINS_ACTION_CONCURRENT_SAVE, PLUGINS_ACTION_CLONE_START, PLUGINS_ACTION_DOWNLOAD_URL_INPUT, PLUGINS_ACTION_CONCURRENT_SLIDER_INPUT, PLUGINS_ACTION_CONCURRENT_VALUE_INPUT, PLUGINS_ACTION_DOWNLOAD_FILE_CHANGE];

const { guard: isPluginsCardActionId } = createActionIdSet<PluginsCardActionId>(...Object.keys(PLUGIN_ACTION_HANDLERS));
const { guard: isPluginsActionId } = createActionIdSet<PluginsActionId>(...Object.keys(PLUGIN_ACTION_HANDLERS), ...PLUGINS_PAGE_ACTION_IDS);

export { PLUGINS_ACTION_SORT_LIST, PLUGINS_ACTION_TOGGLE_VIEW_MODE, isPluginsActionId, isPluginsCardActionId };
export type { PluginsCardActionId, PluginsPageActionId, PluginsPageChangeActionId, PluginsPageClickActionId, PluginsPageInputActionId, PluginsPageRootActionId };
