/* SoAI - Chat page markup [frontend/assets/ts/pages/chat/widgets/conversationtoolbar/markup.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { renderLabelAttributes } from '@core/security/public.ts';
import type { ConversationToolbarStrings } from '@pages/chat/widgets/conversationtoolbar/types.ts';

const buildConversationToolbarMarkup = (strings: ConversationToolbarStrings): string => {
    return `<div class="chat-toolbar-container batch-toolbar-container is-collapsed" id="chat-toolbar-container"><div class="chat-toolbar-collapsed-layer"><button class="chat-toolbar-toggle batch-toolbar-toggle" type="button" data-action="chat:toggle-toolbar" ${renderLabelAttributes(strings.toolbarExpand)}></button></div><div class="chat-toolbar-expanded-layer"><div class="chat-toolbar-content batch-toolbar-content"><div class="chat-toolbar-metrics batch-toolbar-metrics"><span class="chat-toolbar-count-icon batch-toolbar-count-icon chat-toolbar-total-conversations-icon" aria-hidden="true"></span><span class="chat-toolbar-metric chat-toolbar-total-conversations"></span><span class="chat-toolbar-metric chat-toolbar-selected-count u-hidden"></span></div><div class="chat-toolbar-actions batch-toolbar-actions"><button type="button" class="chat-toolbar-open-archived-btn ui-icon-button" data-action="chat:open-archived-conversations" ${renderLabelAttributes(strings.toolbarArchive)}></button><button type="button" class="chat-toolbar-select-btn ui-icon-button" data-action="chat:enter-select-mode" ${renderLabelAttributes(strings.toolbarSelect)}></button></div><div class="chat-toolbar-batch-actions batch-toolbar-batch-actions u-hidden"><button type="button" class="chat-toolbar-batch-archive-btn ui-icon-button u-hidden" data-action="chat:batch-archive" ${renderLabelAttributes(strings.toolbarBatchArchive)} disabled></button><button type="button" class="chat-toolbar-batch-clone-btn ui-icon-button u-hidden" data-action="chat:batch-clone" ${renderLabelAttributes(strings.toolbarBatchClone)} disabled></button><button type="button" class="chat-toolbar-batch-delete-btn ui-icon-button ui-button ui-variant-danger u-hidden" data-action="chat:batch-delete" ${renderLabelAttributes(strings.toolbarBatchDelete)} disabled></button><button type="button" class="chat-toolbar-exit-select-btn ui-icon-button" data-action="chat:exit-select-mode" ${renderLabelAttributes(strings.toolbarExitSelect)}></button></div></div><div class="chat-toolbar-expanded-bottom" data-action="chat:toggle-toolbar"><div class="chat-toolbar-expanded-chevron"><button class="chat-toolbar-expanded-toggle batch-toolbar-toggle" type="button" data-action="chat:toggle-toolbar" ${renderLabelAttributes(strings.toolbarExpand)}></button></div></div></div></div>`;
};

export { buildConversationToolbarMarkup };
