/* SoAI - Metrics feature telemetry stage labels [frontend/assets/ts/features/metrics/telemetryStageLabels.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { i18n } from '@core/i18n/index.ts';

const resolveTelemetryStageBaseLabel = (stageToken: string): string => {
    const normalized = stageToken.replace(/[:]/g, '.').trim();
    switch (normalized) {
        case 'appLifecycle.ready':
            return i18n.t('liveStatusOverlay.events.appLifecycle.ready');
        case 'applyRoute.complete':
            return i18n.t('liveStatusOverlay.events.applyRoute.complete');
        case 'applyRoute.start':
            return i18n.t('liveStatusOverlay.events.applyRoute.start');
        case 'autoResources.state':
            return i18n.t('liveStatusOverlay.events.autoResources.state');
        case 'backend-ready':
            return i18n.t('liveStatusOverlay.events.backend-ready');
        case 'backend.pending':
            return i18n.t('liveStatusOverlay.events.backend.pending');
        case 'backend.ready':
            return i18n.t('liveStatusOverlay.events.backend.ready');
        case 'bootstrap.auth.initialize.complete':
            return i18n.t('liveStatusOverlay.events.bootstrap.auth.initialize.complete');
        case 'bootstrap.auth.initialize.start':
            return i18n.t('liveStatusOverlay.events.bootstrap.auth.initialize.start');
        case 'bootstrap.backend.ready':
            return i18n.t('liveStatusOverlay.events.bootstrap.backend.ready');
        case 'bootstrap.complete':
            return i18n.t('liveStatusOverlay.events.bootstrap.complete');
        case 'bootstrap.error':
            return i18n.t('liveStatusOverlay.events.bootstrap.error');
        case 'bootstrap.failure':
            return i18n.t('liveStatusOverlay.events.bootstrap.failure');
        case 'bootstrap.fatal':
            return i18n.t('liveStatusOverlay.events.bootstrap.fatal');
        case 'bootstrap.navigation.complete':
            return i18n.t('liveStatusOverlay.events.bootstrap.navigation.complete');
        case 'bootstrap.navigation.start':
            return i18n.t('liveStatusOverlay.events.bootstrap.navigation.start');
        case 'bootstrap.route.resolve.complete':
            return i18n.t('liveStatusOverlay.events.bootstrap.route.resolve.complete');
        case 'bootstrap.route.resolve.start':
            return i18n.t('liveStatusOverlay.events.bootstrap.route.resolve.start');
        case 'bootstrap.session.complete':
            return i18n.t('liveStatusOverlay.events.bootstrap.session.complete');
        case 'bootstrap.session.start':
            return i18n.t('liveStatusOverlay.events.bootstrap.session.start');
        case 'bootstrap.start':
            return i18n.t('liveStatusOverlay.events.bootstrap.start');
        case 'bootstrap.streamManager.initialize.complete':
            return i18n.t('liveStatusOverlay.events.bootstrap.streamManager.initialize.complete');
        case 'bootstrap.streamManager.initialize.failed':
            return i18n.t('liveStatusOverlay.events.bootstrap.streamManager.initialize.failed');
        case 'bootstrap.streamManager.initialize.start':
            return i18n.t('liveStatusOverlay.events.bootstrap.streamManager.initialize.start');
        case 'bootstrap.wizard.status':
            return i18n.t('liveStatusOverlay.events.bootstrap.wizard.status');
        case 'cleanup.complete':
            return i18n.t('liveStatusOverlay.events.cleanup.complete');
        case 'cleanup.error':
            return i18n.t('liveStatusOverlay.events.cleanup.error');
        case 'cleanup.start':
            return i18n.t('liveStatusOverlay.events.cleanup.start');
        case 'closed':
            return i18n.t('liveStatusOverlay.events.closed');
        case 'complete':
            return i18n.t('liveStatusOverlay.events.complete');
        case 'component.data.ready':
            return i18n.t('liveStatusOverlay.events.component.data.ready');
        case 'component.load.error':
            return i18n.t('liveStatusOverlay.events.component.load.error');
        case 'component.load.ready':
            return i18n.t('liveStatusOverlay.events.component.load.ready');
        case 'component.load.start':
            return i18n.t('liveStatusOverlay.events.component.load.start');
        case 'component.preload.error':
            return i18n.t('liveStatusOverlay.events.component.preload.error');
        case 'component.preload.ready':
            return i18n.t('liveStatusOverlay.events.component.preload.ready');
        case 'component.preload.start':
            return i18n.t('liveStatusOverlay.events.component.preload.start');
        case 'connected':
            return i18n.t('liveStatusOverlay.events.connected');
        case 'connecting':
            return i18n.t('liveStatusOverlay.events.connecting');
        case 'connection.connected':
            return i18n.t('liveStatusOverlay.events.connection.connected');
        case 'connection.lost':
            return i18n.t('liveStatusOverlay.events.connection.lost');
        case 'connection.timeout':
            return i18n.t('liveStatusOverlay.events.connection.timeout');
        case 'deferred':
            return i18n.t('liveStatusOverlay.events.deferred');
        case 'disconnected':
            return i18n.t('liveStatusOverlay.events.disconnected');
        case 'ensureReady.cached':
            return i18n.t('liveStatusOverlay.events.ensureReady.cached');
        case 'ensureReady.complete':
            return i18n.t('liveStatusOverlay.events.ensureReady.complete');
        case 'ensureReady.error':
            return i18n.t('liveStatusOverlay.events.ensureReady.error');
        case 'ensureReady.start':
            return i18n.t('liveStatusOverlay.events.ensureReady.start');
        case 'error':
            return i18n.t('liveStatusOverlay.events.error');
        case 'hardware.gpu.action':
            return i18n.t('liveStatusOverlay.events.hardware.gpu.action');
        case 'heartbeat.timeout':
            return i18n.t('liveStatusOverlay.events.heartbeat.timeout');
        case 'icons-ready':
            return i18n.t('liveStatusOverlay.events.icons-ready');
        case 'instantiate.complete':
            return i18n.t('liveStatusOverlay.events.instantiate.complete');
        case 'instantiate.created':
            return i18n.t('liveStatusOverlay.events.instantiate.created');
        case 'instantiate.enhanced':
            return i18n.t('liveStatusOverlay.events.instantiate.enhanced');
        case 'instantiate.start':
            return i18n.t('liveStatusOverlay.events.instantiate.start');
        case 'kernel-started':
            return i18n.t('liveStatusOverlay.events.kernel-started');
        case 'kernel.ready':
            return i18n.t('liveStatusOverlay.events.kernel.ready');
        case 'kernel.refresh':
            return i18n.t('liveStatusOverlay.events.kernel.refresh');
        case 'kernel.start':
            return i18n.t('liveStatusOverlay.events.kernel.start');
        case 'language-ready':
            return i18n.t('liveStatusOverlay.events.language-ready');
        case 'metrics.fetchCapabilities':
            return i18n.t('liveStatusOverlay.events.metrics.fetchCapabilities');
        case 'middleware.complete':
            return i18n.t('liveStatusOverlay.events.middleware.complete');
        case 'middleware.error':
            return i18n.t('liveStatusOverlay.events.middleware.error');
        case 'middleware.start':
            return i18n.t('liveStatusOverlay.events.middleware.start');
        case 'models.withLoading':
            return i18n.t('liveStatusOverlay.events.models.withLoading');
        case 'modules-ready':
            return i18n.t('liveStatusOverlay.events.modules-ready');
        case 'mounted':
            return i18n.t('liveStatusOverlay.events.mounted');
        case 'mounting':
            return i18n.t('liveStatusOverlay.events.mounting');
        case 'navigation.middleware.complete':
            return i18n.t('liveStatusOverlay.events.navigation.middleware.complete');
        case 'navigation.middleware.error':
            return i18n.t('liveStatusOverlay.events.navigation.middleware.error');
        case 'navigation.middleware.start':
            return i18n.t('liveStatusOverlay.events.navigation.middleware.start');
        case 'plugins.disablePlugin':
            return i18n.t('liveStatusOverlay.events.plugins.disablePlugin');
        case 'plugins.enablePlugin':
            return i18n.t('liveStatusOverlay.events.plugins.enablePlugin');
        case 'plugins.withLoading':
            return i18n.t('liveStatusOverlay.events.plugins.withLoading');
        case 'prompts.create':
            return i18n.t('liveStatusOverlay.events.prompts.create');
        case 'prompts.update':
            return i18n.t('liveStatusOverlay.events.prompts.update');
        case 'prompts.withLoading':
            return i18n.t('liveStatusOverlay.events.prompts.withLoading');
        case 'ready':
            return i18n.t('liveStatusOverlay.events.ready');
        case 'reconnect.failed':
            return i18n.t('liveStatusOverlay.events.reconnect.failed');
        case 'reconnect.scheduled':
            return i18n.t('liveStatusOverlay.events.reconnect.scheduled');
        case 'router-ready':
            return i18n.t('liveStatusOverlay.events.router-ready');
        case 'snapshot.cache-hit':
            return i18n.t('liveStatusOverlay.events.snapshot.cache-hit');
        case 'snapshot.initial':
            return i18n.t('liveStatusOverlay.events.snapshot.initial');
        case 'snapshot.update':
            return i18n.t('liveStatusOverlay.events.snapshot.update');
        case 'start':
            return i18n.t('liveStatusOverlay.events.start');
        case 'stream-ready':
            return i18n.t('liveStatusOverlay.events.stream-ready');
        case 'stream.detached':
            return i18n.t('liveStatusOverlay.events.stream.detached');
        case 'subscriber.update':
            return i18n.t('liveStatusOverlay.events.subscriber.update');
        case 'websocket.event':
            return i18n.t('liveStatusOverlay.events.websocket.event');
        default:
            return stageToken;
    }
};

export { resolveTelemetryStageBaseLabel };
