/* SoAI - Dashboard movable section layout constants [frontend/assets/ts/pages/dashboard/rendering/layout/constants.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import type { MovableGridSettings } from '@core/routing/pages/movablesections/types.ts';

const DASHBOARD_COLLECTION_VISIBLE_ITEMS = 8;
const DASHBOARD_COLLECTION_ITEM_HEIGHT_PX = 42;
const DASHBOARD_COLLECTION_LIST_GAP_PX = 8;
const DASHBOARD_COLLECTION_LIST_PADDING_BOTTOM_PX = 12;
const DASHBOARD_COLLECTION_SUMMARY_HEIGHT_PX = 58;
const DASHBOARD_COLLECTION_SUMMARY_MARGIN_BOTTOM_PX = 16;
const DASHBOARD_COLLECTION_CONTENT_TOP_PADDING_PX = 12;
const DASHBOARD_SECTION_HEADER_HEIGHT_PX = 36;
const DASHBOARD_SECTION_STATUS_HEIGHT_PX = 3;
const DASHBOARD_WIDGET_VERTICAL_SLACK_PX = 4;
const DASHBOARD_REFERENCE_CELL_WIDTH_PX = 320;
const DASHBOARD_COLLECTION_LIST_HEIGHT_PX = DASHBOARD_COLLECTION_ITEM_HEIGHT_PX * DASHBOARD_COLLECTION_VISIBLE_ITEMS + DASHBOARD_COLLECTION_LIST_GAP_PX * (DASHBOARD_COLLECTION_VISIBLE_ITEMS - 1) + DASHBOARD_COLLECTION_LIST_PADDING_BOTTOM_PX;
const DASHBOARD_COLLECTION_CONTENT_HEIGHT_PX = DASHBOARD_COLLECTION_CONTENT_TOP_PADDING_PX + DASHBOARD_COLLECTION_SUMMARY_HEIGHT_PX + DASHBOARD_COLLECTION_SUMMARY_MARGIN_BOTTOM_PX + DASHBOARD_COLLECTION_LIST_HEIGHT_PX;
const DASHBOARD_BASE_CELL_HEIGHT_PX = DASHBOARD_SECTION_HEADER_HEIGHT_PX + DASHBOARD_COLLECTION_CONTENT_HEIGHT_PX + DASHBOARD_SECTION_STATUS_HEIGHT_PX + DASHBOARD_WIDGET_VERTICAL_SLACK_PX;

const DASHBOARD_GRID_SETTINGS = Object.freeze<MovableGridSettings>({
    columns: 5,
    baseCellHeight: DASHBOARD_BASE_CELL_HEIGHT_PX,
    dragThreshold: 5,
    dragScale: 1.05,
    responsive: {
        type: 'content-scale',
        referenceCellWidth: DASHBOARD_REFERENCE_CELL_WIDTH_PX,
        minimumContentScale: 0.75
    }
});

export { DASHBOARD_GRID_SETTINGS };
