"""SoAI - Assistant timeline activity status sets [backend/features/assistant_timeline/activity_status_sets.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = (
    "TIMELINE_ACTIVITY_EMITTED_STATUSES",
    "TIMELINE_ACTIVITY_RUNNING_STATUSES",
    "TIMELINE_ACTIVITY_STATUS_CANCELLED",
    "TIMELINE_ACTIVITY_STATUS_COMPLETED",
    "TIMELINE_ACTIVITY_STATUS_ERROR",
    "TIMELINE_ACTIVITY_STATUS_IDLE",
    "TIMELINE_ACTIVITY_STATUS_RUNNING",
    "TIMELINE_ACTIVITY_TERMINAL_STATUSES",
    "TIMELINE_ACTIVITY_VALID_STATUSES",
)

TIMELINE_ACTIVITY_STATUS_IDLE = "idle"
TIMELINE_ACTIVITY_STATUS_RUNNING = "running"
TIMELINE_ACTIVITY_STATUS_COMPLETED = "completed"
TIMELINE_ACTIVITY_STATUS_CANCELLED = "cancelled"
TIMELINE_ACTIVITY_STATUS_ERROR = "error"

TIMELINE_ACTIVITY_TERMINAL_STATUSES: frozenset[str] = frozenset(
    (
        TIMELINE_ACTIVITY_STATUS_COMPLETED,
        TIMELINE_ACTIVITY_STATUS_CANCELLED,
        TIMELINE_ACTIVITY_STATUS_ERROR,
    ),
)
TIMELINE_ACTIVITY_RUNNING_STATUSES: frozenset[str] = frozenset((TIMELINE_ACTIVITY_STATUS_RUNNING,))
TIMELINE_ACTIVITY_EMITTED_STATUSES: frozenset[str] = frozenset(
    (
        TIMELINE_ACTIVITY_STATUS_RUNNING,
        TIMELINE_ACTIVITY_STATUS_COMPLETED,
        TIMELINE_ACTIVITY_STATUS_CANCELLED,
        TIMELINE_ACTIVITY_STATUS_ERROR,
    ),
)
TIMELINE_ACTIVITY_VALID_STATUSES: frozenset[str] = frozenset(
    (
        TIMELINE_ACTIVITY_STATUS_IDLE,
        TIMELINE_ACTIVITY_STATUS_RUNNING,
        TIMELINE_ACTIVITY_STATUS_COMPLETED,
        TIMELINE_ACTIVITY_STATUS_CANCELLED,
        TIMELINE_ACTIVITY_STATUS_ERROR,
    ),
)
