"""SoAI - Status preview state key definitions [backend/features/assistant_timeline/status_preview_state_keys.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = ("resolve_status_preview_argument_detail_keys",)


def resolve_status_preview_argument_detail_keys(*, tool_name: str) -> tuple[str, ...]:
    normalized_tool_name = str(tool_name or "").strip()
    if normalized_tool_name == "soai_documentation":
        return ("query", "page")
    if normalized_tool_name.startswith("browser_"):
        return (
            "url",
            "current_page_url",
            "title",
            "query",
            "message",
            "label_suggestion",
            "file_path",
            "path",
            "dir_path",
            "target",
            "name",
            "offset",
            "depth",
            "pattern",
            "location",
            "timezone",
        )
    return (
        "questions",
        "cwd",
        "argv",
        "args",
        "cmd",
        "command",
        "task",
        "query",
        "title",
        "message",
        "prompt",
        "expression",
        "pattern",
        "file_id",
        "files",
        "file_paths",
        "paths",
        "file_path",
        "path",
        "dir_path",
        "url",
        "uri",
        "current_page_url",
        "location",
        "timezone",
        "model",
        "language",
        "mode",
        "display_name",
        "label_suggestion",
        "allow_save_to_vault",
        "subagent_id",
        "context",
        "workspace_path",
        "max_iterations",
        "tools",
        "automation_id",
        "run_id",
        "target",
        "limit",
        "region",
        "country",
        "search_lang",
        "freshness",
        "categories",
        "engines",
        "search_depth",
        "include_domains",
        "exclude_domains",
        "safe",
        "gl",
        "hl",
        "confirm",
        "new_embedding_model",
        "conv_id",
        "session_id",
        "server_id",
        "from_unit",
        "to_unit",
        "name",
        "offset",
        "depth",
        "include",
        "workdir",
        "shell",
        "method",
        "headers",
        "session",
        "body",
        "timeout",
        "max_response_bytes",
        "follow_redirects",
        "detect_blocked",
        "timeout_ms",
    )
