"""SoAI - Status preview constants [backend/features/assistant_timeline/status_preview_constants.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = (
    "STATUS_PREVIEW_IDLE_CHECK_INTERVAL_MS",
    "STATUS_PREVIEW_INITIAL_DELAY_MS",
    "STATUS_PREVIEW_MAX_EXCERPT_CHARS",
    "STATUS_PREVIEW_STALE_INTERVAL_MS",
    "STATUS_PREVIEW_START_COOLDOWN_MS",
    "STATUS_PREVIEW_TOOL_DETAIL_MAX_CHARS",
)

STATUS_PREVIEW_INITIAL_DELAY_MS = 0
STATUS_PREVIEW_STALE_INTERVAL_MS = 15_000
STATUS_PREVIEW_START_COOLDOWN_MS = 3_000
STATUS_PREVIEW_IDLE_CHECK_INTERVAL_MS = 60_000
STATUS_PREVIEW_MAX_EXCERPT_CHARS = 240
STATUS_PREVIEW_TOOL_DETAIL_MAX_CHARS = 240
