/* SoAI - Indicators feature constants [frontend/assets/ts/features/indicators/constants.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

const LIVE_STATUS_OVERLAY_SERVICE_ID = 'features.indicators.liveStatusOverlay';
const LIVE_STATUS_OVERLAY_ELEMENT_ID = 'live-status-overlay';
const LIVE_STATUS_OVERLAY_REFRESH_INTERVAL_MS = 15000;
const LIVE_STATUS_OVERLAY_STORAGE_READY_TIMEOUT_MS = 5000;
const LIVE_STATUS_OVERLAY_MAX_BUNDLES = 6;
const LIVE_STATUS_OVERLAY_SETTING_CHANGED_EVENT = 'soai:liveStatusOverlay:changed';

export { LIVE_STATUS_OVERLAY_ELEMENT_ID, LIVE_STATUS_OVERLAY_MAX_BUNDLES, LIVE_STATUS_OVERLAY_REFRESH_INTERVAL_MS, LIVE_STATUS_OVERLAY_SERVICE_ID, LIVE_STATUS_OVERLAY_SETTING_CHANGED_EVENT, LIVE_STATUS_OVERLAY_STORAGE_READY_TIMEOUT_MS };
