/* SoAI - Chat feature action IDs [frontend/assets/ts/features/chat/chatActionIds.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';
import { CHAT_ACTION_ID_OPEN_MODEL_DETAIL, CHAT_ACTION_ID_SECRET_PROMPT_CANCEL, CHAT_ACTION_ID_SECRET_PROMPT_SUBMIT } from '@features/chat/chatConstants.ts';

export const CHAT_ACTIONS = Object.freeze({
    NEW_CONVERSATION: 'chat:new-conversation',
    TOGGLE_SIDEBAR: 'chat:toggle-sidebar',
    TOGGLE_FAVORITES_AT_TOP: 'chat:toggle-favorites',
    TOGGLE_CONFIGURATION: 'chat:toggle-configuration',
    OPEN_FILES_FOLDER_SETTINGS: 'chat:open-files-folder-settings',
    EXPORT_CONVERSATION: 'chat:export-conversation',
    GOTO_PROMPTS: 'chat:goto-prompts',
    TOGGLE_TOOLS: 'chat:toggle-tools',
    OPEN_MEMORY_PROFILE: 'chat:open-memory-profile',
    REFRESH_MEMORY: 'chat:refresh-memory',
    GOTO_SETTINGS_MCP: 'chat:goto-settings-mcp',
    EXPORT_CONVERSATION_ITEM: 'chat:export-conversation-item',
    GOTO_MODEL_SETTINGS: 'chat:goto-model-settings',
    GOTO_MODELS_DOWNLOAD: 'chat:goto-models-download',
    SEND_OR_STOP: 'chat:send-or-stop',
    STOP_STREAMING: 'chat:stop-streaming',
    CYCLE_TOKEN_COUNTER: 'chat:cycle-token-counter',
    OPEN_CHARACTER_MAP: 'chat:open-character-map',
    OPEN_ATTACH_MODAL: 'chat:open-attach-modal',
    OPEN_CAMERA: 'chat:open-camera',
    CANCEL_RAG_INGESTION: 'chat:cancel-rag-ingestion',
    TOGGLE_RECORDING: 'chat:toggle-recording',
    CANCEL_RECORDING: 'chat:cancel-recording',
    TOGGLE_CALL: 'chat:toggle-call',
    REFRESH_PRESETS: 'chat:refresh-presets',
    RESET_PRESETS: 'chat:reset-presets',
    NEW_PRESET: 'chat:new-preset',
    APPLY_PRESET: 'chat:preset-apply',
    REPLACE_PRESET: 'chat:preset-replace',
    RENAME_PRESET: 'chat:preset-rename',
    REMOVE_PRESET: 'chat:preset-remove',
    SUBMIT_PRESET_EDITOR: 'chat:preset-editor-submit',
    CANCEL_PRESET_EDITOR: 'chat:preset-editor-cancel',
    REVIEW_PRESET_EDITOR: 'chat:preset-editor-review',
    RESTORE_PARAMETER_DEFAULTS: 'chat:restore-parameter-defaults',
    SAVE_CONFIGURATION: 'chat:save-configuration',
    DELETE_CONVERSATION: 'chat:delete-conversation',
    ARCHIVE_CONVERSATION: 'chat:archive-conversation',
    OPEN_CONVERSATION_COLOR_PICKER: 'chat:open-conversation-color-picker',
    TOGGLE_CURRENT_CONVERSATION_FAVORITE: 'chat:toggle-current-favorite',
    SWITCH_CONVERSATION: 'chat:switch-conversation',
    START_CONVERSATION_RENAME: 'chat:start-conversation-rename',
    START_CONVERSATION_TITLE_EDIT: 'chat:start-conversation-title-edit',
    SUGGESTION: 'chat:suggestion',
    REMOVE_ATTACHED_FILE: 'chat:remove-attached-file',
    REMOVE_DRAFT_KNOWLEDGE_ATTACHMENT: 'chat:remove-draft-knowledge-attachment',
    REMOVE_CONVERSATION_INPUT: 'chat:remove-conversation-input',
    RETRY_CONVERSATION_REGENERATION: 'chat:retry-conversation-regeneration',
    ASK_USER_SELECT_OPTION: 'chat:ask-user-select-option',
    ASK_USER_SUBMIT: 'chat:ask-user-submit',
    ASK_USER_CANCEL: 'chat:ask-user-cancel',
    SECRET_PROMPT_SUBMIT: CHAT_ACTION_ID_SECRET_PROMPT_SUBMIT,
    SECRET_PROMPT_CANCEL: CHAT_ACTION_ID_SECRET_PROMPT_CANCEL,
    TOOL_APPROVAL_APPROVE: 'chat:tool-approval-approve',
    TOOL_APPROVAL_DENY: 'chat:tool-approval-deny',
    CONVERSATION_TITLE_SAVE: 'chat:conversation-title-save',
    CONVERSATION_TITLE_CANCEL: 'chat:conversation-title-cancel',
    CONVERSATION_LIST_TITLE_SAVE: 'chat:conversation-list-title-save',
    CONVERSATION_LIST_TITLE_CANCEL: 'chat:conversation-list-title-cancel',
    COPY_CODE_BLOCK: 'chat:copy-code-block',
    SORT_MARKDOWN_TABLE: 'chat:sort-markdown-table',
    COPY_INLINE_MEDIA_REFERENCE: 'chat:copy-inline-media-reference',
    OPEN_INLINE_LOCAL_FOLDER: 'chat:open-inline-local-folder',
    OPEN_ATTACHMENT_OVERFLOW: 'chat:open-attachment-overflow',
    OPEN_KNOWLEDGE_ATTACHMENT_PREVIEW: 'chat:open-knowledge-attachment-preview',
    OPEN_SOAI_FILE_PREVIEW: 'chat:open-soai-file-preview',
    OPEN_SOAI_PATH_PREVIEW: 'chat:open-soai-path-preview',
    REVEAL_RUNNING_ACTIVITY: 'chat:reveal-running-activity',
    TOGGLE_LOADING_ACTIVITY_ITEM: 'chat:toggle-loading-activity-item',
    TOGGLE_TOOL_ACTIVITY_ITEM: 'chat:toggle-tool-activity-item',
    OPEN_TOOL_CALL_OUTPUT: 'chat:open-tool-call-output',
    REMOVE_COMPACTION_BOUNDARY: 'chat:remove-compaction-boundary',
    STOP_SHELL: 'chat:stop-shell-command',
    OPEN_MULTIMEDIA_PREVIEW: 'chat:open-multimedia-preview',
    DOWNLOAD_MULTIMEDIA: 'chat:download-multimedia',
    OPEN_MULTIMEDIA_SOURCE: 'chat:open-multimedia-source',
    CYCLE_AGENT_MODE: 'chat:cycle-agent-mode',
    COMPACT_AGENT: 'chat:compact-agent',
    TOGGLE_TODO_PANEL: 'chat:toggle-todo-panel',
    TOGGLE_PLAN_BAR: 'chat:toggle-plan-bar',
    VIEW_AGENT_PLAN: 'chat:view-agent-plan',
    EXECUTE_AGENT_PLAN: 'chat:execute-agent-plan',
    TOGGLE_TOOLBAR: 'chat:toggle-toolbar',
    COMPARISON_PREV: 'chat:comparison-prev',
    COMPARISON_NEXT: 'chat:comparison-next',
    MODEL_CONTROL_TOGGLE_MENU: 'chat:model-control-toggle-menu',
    MODEL_CONTROL_SELECT_MODEL: 'chat:model-control-select-model',
    MODEL_CONTROL_ADD_MODEL: 'chat:model-control-add-model',
    MODEL_CONTROL_REMOVE_MODEL: 'chat:model-control-remove-model',
    ENTER_SELECT_MODE: 'chat:enter-select-mode',
    EXIT_SELECT_MODE: 'chat:exit-select-mode',
    BATCH_DELETE: 'chat:batch-delete',
    BATCH_ARCHIVE: 'chat:batch-archive',
    BATCH_CLONE: 'chat:batch-clone',
    OPEN_ARCHIVED_CONVERSATIONS: 'chat:open-archived-conversations',
    UPLOAD_USER_AVATAR: 'chat:upload-user-avatar',
    REMOVE_USER_AVATAR: 'chat:remove-user-avatar',
    UPLOAD_ASSISTANT_AVATAR: 'chat:upload-assistant-avatar',
    REMOVE_ASSISTANT_AVATAR: 'chat:remove-assistant-avatar',
    OPEN_MODEL_DETAIL: CHAT_ACTION_ID_OPEN_MODEL_DETAIL,
    SELECT_CONVERSATION_COLOR: 'select-conversation-color',
    TOGGLE_CONVERSATION_FAVORITE: 'toggle-conversation-favorite',
    COPY_TIMESTAMP: 'copy-timestamp',
    DELETE: 'delete',
    DELETE_NOW: 'delete-now',
    DELETE_UNDO: 'delete-undo',
    COPY: 'copy',
    SPEAK: 'speak',
    RESEND: 'resend',
    EDIT: 'edit',
    EDIT_SAVE: 'edit-save',
    EDIT_CANCEL: 'edit-cancel',
    INFO: 'info',
    REGENERATE: 'regenerate'
});

export type ChatActionId = (typeof CHAT_ACTIONS)[keyof typeof CHAT_ACTIONS];

export const { guard: isChatActionId } = createActionIdSet<ChatActionId>(...Object.values(CHAT_ACTIONS));
