/* SoAI - Chat feature public surface [frontend/assets/ts/features/chat/public.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

export { agentCheckpointTargetsConversationMessageRange } from '@features/chat/agent/agentCheckpointMessageRange.ts';
export { rehydrateTurnStateFromCheckpoint } from '@features/chat/agent/agentCheckpointRehydration.ts';
export { isCompactionConflictError, startManualCompaction } from '@features/chat/agent/agentCompactionControl.ts';
export { ensureManualCompactionAssistantPlaceholder } from '@features/chat/agent/agentCompactionPlaceholder.ts';
export { requestAgentCheckpointSnapshot, requestAgentPlanSnapshot, requestAgentTodoSnapshot } from '@features/chat/agent/agentStateSnapshotRequests.ts';
export { createAgentEventHandler } from '@features/chat/agent/agentEventHandler.ts';
export type { AgentEventHandlerResult } from '@features/chat/agent/agentEventHandler.ts';
export { createAgentInputController } from '@features/chat/agent/agentInputController.ts';
export type { AgentInputController } from '@features/chat/agent/agentInputController.ts';
export { handleExternalModeChange, selectAndPersistAgentMode } from '@features/chat/agent/agentModeController.ts';
export { applyAgentModeBorderIndicator } from '@features/chat/agent/agentModeIndicator.ts';
export { resolveAgentModeLabel } from '@features/chat/agent/agentModeLabels.ts';
export { isAgentMode, resolveAgentMode } from '@features/chat/agent/agentModeState.ts';
export { updateAgentTodoPanelElement } from '@features/chat/agent/agentTodoPanel.ts';
export { getTurnStateForConversation } from '@features/chat/agent/agentTurnStateManager.ts';
export { canResolveAssistantMessageByLogicalIndex, resolveAssistantMessageByLogicalIndex, resolveAssistantMessageTarget } from '@features/chat/agent/agentMessageTargetResolution.ts';
export type { AgentAssistantMessageTarget } from '@features/chat/agent/agentMessageTargetResolution.ts';
export { buildAgentAssistantEventTimeline, combineIterationText, hasChatStreamLoadingActivityTimeline } from '@features/chat/agent/agentAssistantTimelineProjection.ts';
export { countAgentTextCodePoints } from '@features/chat/agent/agentTextMetrics.ts';
export { buildChronologicalToolActivity } from '@features/chat/agent/agentChronologicalToolActivity.ts';
export type { TimelineToolActivityItem } from '@features/chat/agent/agentChronologicalToolActivity.ts';
export { buildParentToolCallResultPayload } from '@features/chat/agent/agentSubagentToolResult.ts';
export { buildSubagentParentToolCallId, isSubagentParentToolCallId, resolveSubagentIdFromParentToolCallId } from '@features/chat/agent/subagentCallIds.ts';
export type { AskUserPrompt } from '@features/chat/askuser/askUserModels.ts';
export { parseAskUserPendingResponse } from '@features/chat/askuser/askUserModels.ts';
export { focusAskUserPrompt, getAskUserPredefinedOptionButtons, getAskUserQuestionElements, getAskUserSelectedPredefinedOptionButtons, optionalAskUserCancelButton, optionalAskUserOtherButton, optionalAskUserPreview, optionalAskUserQuestionRootFromChild, optionalAskUserSubmitButton, optionalAskUserTextInput, optionalAskUserTextInputWrapper } from '@features/chat/askuser/dom.ts';
export { buildAskUserPreviewMarkup } from '@features/chat/askuser/askUserPreviewMarkup.ts';
export { isAgentModeRequiringTools } from '@features/chat/conversationsettings/mcpToolsActiveState.ts';
export { applyMcpToolsToggleButtonState } from '@features/chat/conversationsettings/mcpToolsToggleButtonState.ts';
export type { SecretPrompt } from '@features/chat/secretprompt/secretPromptModels.ts';
export { parseSecretPromptPendingResponse } from '@features/chat/secretprompt/secretPromptModels.ts';
export { focusSecretPrompt, optionalSecretPromptInput, optionalSecretPromptRootFromChild, optionalSecretPromptSaveCheckbox, setSecretPromptLabelVisibility } from '@features/chat/secretprompt/dom.ts';
export { buildSecretPromptPreviewMarkup } from '@features/chat/secretprompt/secretPromptPreviewMarkup.ts';
export type { ToolApprovalPrompt } from '@features/chat/toolapproval/toolApprovalModels.ts';
export { parseToolApprovalPendingResponse } from '@features/chat/toolapproval/toolApprovalModels.ts';
export { focusToolApprovalPrompt, optionalToolApprovalRememberToggle } from '@features/chat/toolapproval/dom.ts';
export { buildToolApprovalPreviewMarkup } from '@features/chat/toolapproval/toolApprovalPreviewMarkup.ts';
export { ChatElicitationSession } from '@features/chat/elicitation/ChatElicitationSession.ts';
export { ChatElicitationPreview } from '@features/chat/elicitation/ChatElicitationPreview.ts';
export type { ChatElicitationSessionDependencies, ElicitationApi, ElicitationType } from '@features/chat/elicitation/ChatElicitationSession.ts';
export { registerAbortListener } from '@features/chat/abort/abortSignalListener.ts';
export { processAvatarFile } from '@features/chat/avatar/service.ts';
export { ChatPagePresenceService } from '@features/chat/background/ChatPagePresenceService.ts';
export { ChatConversationAttentionService } from '@features/chat/background/ChatConversationAttentionService.ts';
export { ChatAttachmentManager } from '@features/chat/ChatAttachmentManager.ts';
export { ChatComposerDraftManager } from '@features/chat/composerdraft/ChatComposerDraftManager.ts';
export type { ComposerDraftTransferMode } from '@features/chat/composerdraft/ComposerDraftOwnershipState.ts';
export type { ComposerDraftFlushOptions } from '@features/chat/composerdraft/composerDraftTypes.ts';
export { buildDraftAttachmentOverflowRecords } from '@features/chat/attachments/draftAttachmentOverflowRecords.ts';
export { createLinkedKnowledgeClientBatchId } from '@features/chat/attachments/linkedKnowledgeClientBatchId.ts';
export type { LinkedKnowledgeClientBatchSelection } from '@features/chat/attachments/linkedKnowledgeClientBatchId.ts';
export { isChatAttachmentReadyForSend } from '@features/chat/ChatAttachmentSupport.ts';
export { isSupportedChatImageFile } from '@features/chat/ChatAttachmentSupport.ts';
export { cloneSoaiPathDraftRecordContentPart, isSoaiPathDraftRecord, parseSoaiPathDraftRecords, resolveSoaiPathDraftRecordTitle, resolveSoaiPathDraftRecordToken } from '@features/chat/attachments/soaiPathDraftRecords.ts';
export { normalizeSoaiPathStoragePart } from '@features/chat/attachments/soaiPathContentPart.ts';
export type { SoaiPathStoragePart } from '@features/chat/attachments/soaiPathContentPart.ts';
export { captureSoaiLinkWorkspaceSnapshot, matchesSoaiLinkWorkspaceSnapshot } from '@features/chat/attachments/soaiLinkWorkspaceSnapshot.ts';
export { requireMatchingResolveContentParts, requireMatchingResolveRecords } from '@features/chat/attachments/soaiLinkResolveValidation.ts';
export type { SoaiPathDraftRecord } from '@features/chat/attachments/soaiPathDraftRecords.ts';
export { transcribeAudioBlob } from '@features/chat/api/webuiMediaAudio.ts';
export { ChatAudioManager } from '@features/chat/ChatAudioManager.ts';
export { readChatErrorPresentation, resolveChatErrorDetailText, resolveChatRequestErrorNotificationMessage, resolveTokenCounterErrorNotificationMessage } from '@features/chat/chatErrorPresentation.ts';
export type { AudioRecordingSnapshot, AudioState } from '@features/chat/ChatAudioManager.ts';
export { ChatColorToolkit } from '@features/chat/ChatColorToolkit.ts';
export { CHAT_ACTION_ID_OPEN_MODEL_DETAIL, CHAT_ACTION_ID_SECRET_PROMPT_CANCEL, CHAT_ACTION_ID_SECRET_PROMPT_SUBMIT, CHAT_CHARACTER_MAP_BUTTON_CLASS, CHAT_EVENT_MODEL_SELECTION_CHANGED, CONVERSATION_TITLE_MAX_LENGTH, CHAT_MOBILE_SIDEBAR_BREAKPOINT_PX, CHAT_ACTIVITY_COMPACT_BREAKPOINT_PX, CHAT_ATTACHMENT_INLINE_LIMIT, CHAT_ICON_SIZE_MD, CHAT_ICON_SIZE_SM, CHAT_ICON_SIZE_XS, CHAT_SELECTORS } from '@features/chat/chatConstants.ts';
export { CHAT_CHARACTER_MAP_MODAL_ID } from '@features/chat/modals/constants.ts';
export { CHARACTER_MAP_ACTIONS, isCharacterMapAction } from '@features/chat/charactermap/actions.ts';
export type { CharacterMapAction } from '@features/chat/charactermap/actions.ts';
export { CharacterMapCatalogIndex } from '@features/chat/charactermap/catalog.ts';
export { decodeCharacterMapCatalog } from '@features/chat/charactermap/catalogDecoder.ts';
export { CHARACTER_MAP_DEFAULT_FONT_ID, CHARACTER_MAP_FONT_CLASSES, CHARACTER_MAP_FONTS, getCharacterMapFont, isCharacterMapFontId } from '@features/chat/charactermap/fontCatalog.ts';
export type { CharacterMapFontId } from '@features/chat/charactermap/fontCatalog.ts';
export type { CharacterMapCatalog } from '@features/chat/charactermap/catalogContracts.ts';
export type { CharacterMapQueryResult, CharacterMapResultItem } from '@features/chat/charactermap/catalog.ts';
export { preflightComparisonTurn } from '@features/chat/comparisonTurnPreflight.ts';
export type { ComparisonTurnPreflightResult, ComparisonTurnPreflightVariant } from '@features/chat/comparisonTurnPreflight.ts';
export { isComparisonOnlyAssistantVariant, resolveComparisonTurnStatesByTurn, resolveChatComparisonTurnMeta } from '@features/chat/comparisonTurnMetadata.ts';
export type { ChatComparisonTurnInvalidReason, ChatComparisonTurnState } from '@features/chat/comparisonTurnMetadata.ts';
export type { ChatComparisonTurnRenderModel } from '@features/chat/comparisonTurnRenderModel.ts';
export { countLogicalConversationMessages } from '@features/chat/conversation/rendering/logicalMessageCount.ts';
export { analyzeConversationProjection } from '@features/chat/conversation/rendering/conversationProjectionAnalysis.ts';
export type { ConversationProjectionAnalysis } from '@features/chat/conversation/rendering/conversationProjectionAnalysis.ts';
export { resolveRenderableConversationEntries } from '@features/chat/conversation/rendering/conversationEntries.ts';
export type { ComparisonTurnRenderEntry, ComparisonTurnVariantEntry, ConversationRenderEntry, MessageRenderEntry } from '@features/chat/conversation/rendering/conversationEntries.ts';
export { buildConversationExportCoverData } from '@features/chat/conversationexport/coverData.ts';
export type { ConversationExportCoverData, ConversationExportOutlineEntry, ConversationExportSummaryItem } from '@features/chat/conversationexport/coverData.ts';
export type { ConversationExportModelCategory, ConversationExportModelDescriptor, ConversationExportModelResolver } from '@features/chat/conversationexport/coverData.ts';
export { buildConversationExportCoverDocument } from '@features/chat/conversationexport/coverDocument.ts';
export { enhanceConversationExportInlineMedia } from '@features/chat/conversationexport/inlineMedia.ts';
export { PDF_COLOR_ACCENT, PDF_COLOR_ASSISTANT_SURFACE, PDF_COLOR_EXACT_RULES, PDF_COLOR_HEADING, PDF_FONT_STACK_SANS, PDF_PAGE_RULE } from '@features/chat/conversationexport/pdfDocumentTokens.ts';
export { renderConversationExportMessages } from '@features/chat/conversationexport/rendering.ts';
export { resolveConversationRenderEntrySignature } from '@features/chat/conversation/rendering/entrySignatures.ts';
export { CHAT_ACTIONS, isChatActionId } from '@features/chat/chatActionIds.ts';
export type { ChatActionId } from '@features/chat/chatActionIds.ts';
export { CHAT_ATTACH_MODAL_ACTIONS, isChatAttachModalAction } from '@features/chat/composerattachmodal/actions.ts';
export { createCameraCaptureRuntime } from '@features/chat/composerattachmodal/cameraCapture.ts';
export type { ChatAttachModalAction } from '@features/chat/composerattachmodal/actions.ts';
export type { ChatAttachCameraElements, ChatAttachCameraRuntime } from '@features/chat/composerattachmodal/cameraCapture.ts';
export { ARCHIVED_CONVERSATIONS_MODAL_ID, CHAT_ATTACH_MODAL_ID, CHAT_ATTACHMENT_OVERFLOW_MODAL_ID, CHAT_PROMPTS_PICKER_MODAL_ID, CHAT_TOOL_CALL_OUTPUT_MODAL_ID, CHAT_VOICE_CALL_MODAL_ID } from '@features/chat/modals/constants.ts';
export { MESSAGE_INFO_MODAL_ID } from '@features/chat/message/messageinfomodal/constants.ts';
export { ChatConversationManager } from '@features/chat/ChatConversationManager.ts';
export { ChatPageEmptyState } from '@features/chat/ChatEmptyState.ts';
export { ChatParameterManager } from '@features/chat/ChatParameterManager.ts';
export { isChatMessage } from '@features/chat/message/chatMessageGuards.ts';
export { resolveConversationEntryElements } from '@features/chat/message/conversationEntryElements.ts';
export { setRunningActivityRevealPending } from '@features/chat/message/messageRunningActivitySummaryMarkup.ts';
export { hasPersistedMessageId } from '@features/chat/message/persistedMessageIdentity.ts';
export { applyMarkdownTableSort, isMarkdownTableHeaderLinkTarget, resolveMarkdownTableSortHeader } from '@features/chat/message/markdownTableSorting.ts';
export { hasTerminalAssistantState } from '@features/chat/message/assistantTerminalState.ts';
export type { ActiveComparisonRun } from '@features/chat/message/activeStreamingAssistantMessage.ts';
export { isSoaiFilePreviewType } from '@features/chat/attachments/attachmentPreviewTypes.ts';
export type { SoaiFilePreviewType } from '@features/chat/attachments/attachmentPreviewTypes.ts';
export { ChatSoaiFileContentPreview } from '@features/chat/message/soaiFileContentPreview.ts';
export type { ChatSoaiFileContentPreviewOpenArguments } from '@features/chat/message/soaiFileContentPreview.ts';
export { openKnowledgeAttachmentFirstPreview } from '@features/chat/message/knowledgeAttachmentFirstPreview.ts';
export { resolveKnowledgeAttachmentPreviewText, resolveKnowledgeAttachmentPreviewTitle } from '@features/chat/message/knowledgeAttachmentPreviewPayload.ts';
export { ChatSoaiPathContentPreview } from '@features/chat/message/soaiPathContentPreview.ts';
export type { ChatSoaiPathContentPreviewOpenArguments } from '@features/chat/message/soaiPathContentPreview.ts';
export { ChatStreamService } from '@features/chat/chatstreamservice/service.ts';
export type { StreamUpdate } from '@features/chat/chatstreamservice/types.ts';
export { buildConversationListMarkup } from '@features/chat/chattemplates/conversationListMarkup.ts';
export { buildArchivedConversationRowsMarkup } from '@features/chat/chattemplates/archivedConversationRowMarkup.ts';
export { parseArchivedConversationSearchResponse, parseArchivedConversationsPage, parseBackendConversationRecord } from '@features/chat/storage/conversationPayloadParsing.ts';
export type { ArchivedConversationSummary, ArchivedConversationsCursor, ArchivedConversationsPage, MessageCursor } from '@features/chat/storage/storageModels.ts';
export { requireSanitizer } from '@features/chat/chattemplates/sanitizer.ts';
export { resolveTemplateStrings } from '@features/chat/chattemplates/stringSet.ts';
export type { ChatTemplateStringSet } from '@features/chat/chattemplates/stringSetTypes.ts';
export type { ConversationListItem, ConversationListOptions } from '@features/chat/chattemplates/types.ts';
export { ChatTtsManager } from '@features/chat/ChatTtsManager.ts';
export { renderChatMobileAuxiliaryActionButton, renderChatMobileAuxiliaryActionSelectOptions, resolveChatMobileAuxiliaryActionDescriptor } from '@features/chat/inputactions/mobileAuxiliaryActionCatalog.ts';
export type { ChatMobileAuxiliaryActionDescriptor } from '@features/chat/inputactions/mobileAuxiliaryActionCatalog.ts';
export type { AssistantEventTimelineItem, ChatAttachment, ChatContentSegment, ChatMessage, ConversationContract, ConversationMessage, SoaiCompactionMarker, ToolActivityCodeDiff, ToolActivityItem } from '@features/chat/ChatTypes.ts';
export { ChatUIManager } from '@features/chat/ChatUIManager.ts';
export type { ChatComposerActionMode } from '@features/chat/chatuimanager/types.ts';
export { captureFirstVisibleMessageAnchor, restoreMessageScrollAnchor } from '@features/chat/chatuimanager/messageWindowScrollAnchor.ts';
export type { MessageWindowScrollAnchor } from '@features/chat/chatuimanager/messageWindowScrollAnchor.ts';
export { canInteractivelyAdjustConversationTools, isAutomationConversation, isChatConversationSettingsWritable, isMessagingAccountConversation } from '@features/chat/conversation/conversationSettingsEligibility.ts';
export { parseConversationBatchDeleteResponse } from '@features/chat/conversation/conversationBatchDeleteResponse.ts';
export { compareConversationRecency, resolveMostRecentConversation, resolveReusableNewConversationId } from '@features/chat/conversation/conversationSelectionPolicy.ts';
export { isManagedConfigurationTabHidden, MANAGED_HIDDEN_CONFIGURATION_TAB_IDS } from '@features/chat/conversation/managedConversationCapabilities.ts';
export type { ChatInputActionName } from '@features/chat/conversation/managedConversationCapabilities.ts';
export { CHAT_CONFIGURATION_TAB_DEFINITIONS, isChatConfigurationParameterTabId, resolveChatConfigurationTabId, resolveChatConfigurationTabLabel } from '@features/chat/conversationsettings/chatConfigurationTabs.ts';
export type { ChatConfigurationTabDefinition, ChatConfigurationTabId } from '@features/chat/conversationsettings/chatConfigurationTabs.ts';
export { CHAT_PRESET_SECTION_DEFINITIONS, isChatPresetSectionId, translateChatPresetSection } from '@features/chat/conversationsettings/chatPresetSections.ts';
export type { ChatPresetSectionDefinition, ChatPresetSectionId } from '@features/chat/conversationsettings/chatPresetSections.ts';
export { isConversationEmpty, isProtectedEmptyConversation, limitConversationTitleLength, resolveConversationDisplayTitleFromConversation, sanitizeTitle } from '@features/chat/conversationFormatting.ts';
export { ChatConversationSettingsManager } from '@features/chat/conversationsettings/ChatConversationSettingsManager.ts';
export { disposeChatController, runDisposerCallbacks } from '@features/chat/controllerLifecycle.ts';
export type { ConversationSettingsActionInput, ConversationSettingsActionResult, ConversationSettingsHost, ConversationSettingsSavePlanInput } from '@features/chat/conversationsettings/conversationSettingsHost.ts';
export { parseConversationWorkspacePathConfig, parseMcpConfig, parseMcpTools, parseRagConfig, parseRagDocumentsPage } from '@features/chat/conversationsettings/conversationSettingsParsing.ts';
export { countProcessingRagDocuments, isRagDocumentProcessingStatus } from '@features/chat/conversationsettings/ragDocumentStatus.ts';
export { renderRagDocumentsList } from '@features/chat/conversationsettings/ragDocumentsList.ts';
export { isToolsEffectivelyEnabled } from '@features/chat/conversationsettings/mcpToolsActiveState.ts';
export { renderMcpDefaultToolsModal, renderMcpDefaultToolsSummary, renderMcpServers, renderMcpTools } from '@features/chat/conversationsettings/mcpConversationSettingsUi.ts';
export { isMcpConversationActionId } from '@features/chat/conversationsettings/mcpconversationsettingscontroller/actionIds.ts';
export type { McpConversationActionId } from '@features/chat/conversationsettings/mcpconversationsettingscontroller/actionIds.ts';
export type { ConversationWorkspacePathConfig, McpConfig, McpFormValues, McpTool, McpToolMode, RagConfig, RagDocument, RagDocumentsPage } from '@features/chat/conversationsettings/settingsModels.ts';
export type { ConversationSettingsControllerBundle } from '@features/chat/conversationsettings/controllerRegistry.ts';
export type { IdentityPromptsSnapshot } from '@features/chat/conversationsettings/identitypromptsconversationsettingscontroller/identityPromptsSnapshot.ts';
export { deriveHypotheticalKnowledgeMcpConfig, mergeMcpPreset, snapshotMcpPreset } from '@features/chat/conversationsettings/mcpconversationsettingscontroller/mcpPresetStaging.ts';
export { hasMcpConfigChanges } from '@features/chat/conversationsettings/mcpconversationsettingscontroller/configComparison.ts';
export { compareParameterValues } from '@features/chat/conversationsettings/valueComparison.ts';
export { syncRagUploadProgress } from '@features/chat/conversationsettings/ragconversationsettings/uploadProgress.ts';
export type { RagIngestionAttachmentSource, RagIngestionStatus } from '@features/chat/ingestion/types.ts';
export { isIndexedToPersistedMessageDomIdUpgrade, normalizeMessageDomId, resolveIndexedMessageDomPosition, resolveMessageDomId, resolveConversationInputMessageIdentifierFromMessage, resolvePersistedMessageIdentifier } from '@features/chat/message/messageDomIds.ts';
export { resolveAssistantSemanticIdentityKey } from '@features/chat/message/assistantMessageIdentity.ts';
export { applyChatMessageDeletedExitAnimation, applyChatMessageEnterAnimation, prefersReducedMotion } from '@features/chat/message/messageMotion.ts';
export { extractSpeechTextFromHtml, extractSpeechTextFromMarkdown } from '@features/chat/message/messageSpeech.ts';
export { resolveChatMessageActiveStreamingSignature, resolveChatMessageRenderSignature } from '@features/chat/message/messageRenderSignature.ts';
export { resolveContextCompactionBoundaryRenderModel } from '@features/chat/message/contextcompaction/renderModel.ts';
export type { AssistantRenderIntent } from '@features/chat/message/assistantRenderTransaction.ts';
export { resolveAssistantMutationPostRenderType } from '@features/chat/message/assistantMutationPostRenderPolicy.ts';
export { applyConversationEntryMutation } from '@features/chat/message/conversationEntryMutation.ts';
export { withAssistantViewportStability } from '@features/chat/message/assistantViewportStability.ts';
export { preserveChatMessageInlineState, restoreChatMessageInlineState } from '@features/chat/message/chatMessageInlineStatePreservation.ts';
export { hasSettledAssistantActionsChrome, patchAssistantMessageActionsInPlace } from '@features/chat/message/assistantMessageActionsPatching.ts';
export { patchRenderedAssistantMessageInConversation } from '@features/chat/message/assistantMessageDomPatch.ts';
export { isChatMessageDomOwnedByLiveContainer } from '@features/chat/message/messageDomOwnership.ts';
export { clearAssistantHeaderActivityCatalogStatus, syncAssistantHeaderActivityCatalogStatus } from '@features/chat/message/assistantHeaderCatalogStatus.ts';
export type { MessageSegment } from '@features/chat/message/messageSegments.ts';
export { isEmptyAssistantPlaceholderMessage } from '@features/chat/message/placeholderAssistantMessage.ts';
export { isAssistantMessageRole } from '@features/chat/message/messageRole.ts';
export { resolveConversationExportSenderLabel, resolveMessageSenderLabel } from '@features/chat/message/senderLabel.ts';
export type { MessageSenderLabelContext } from '@features/chat/message/senderLabel.ts';
export { formatThinkingPreviewLabel } from '@features/chat/message/messageview/inlineActivityText.ts';
export { resolveAssistantHeaderDurationArguments } from '@features/chat/message/messageview/assistantHeaderDuration.ts';
export { resolveInlineActivityDurationLabel } from '@features/chat/message/messageview/inlineActivityDuration.ts';
export { removeInlineActivityDuration, syncRunningInlineActivityDuration, syncSettledInlineActivityDuration } from '@features/chat/message/messageview/inlineActivityDurationDomSync.ts';
export { removeAssistantHeaderDuration, syncRunningAssistantHeaderDuration } from '@features/chat/stream/assistantHeaderDurationDomSync.ts';
export type { ChatActivityDurationDisplayMode } from '@features/chat/message/messageview/activityDurationDisplay.ts';
export { resolveActivityDurationDisplayMode } from '@features/chat/message/messageview/activityDurationDisplay.ts';
export type { InlineActivityDurationSyncResult } from '@features/chat/message/messageview/inlineActivityDurationDomSync.ts';
export { resolveInlineToolActivityDurationLabel } from '@features/chat/message/messageview/inlineToolDurationLabel.ts';
export { stripPreviewReferenceTokensForClipboard, stripPreviewReferenceTokensForPlainText } from '@features/chat/message/enhancers/inlineMultimediaPreviewContract.ts';
export { CONTENT_PREVIEW_REASON_CODES, CONTENT_PREVIEW_STATUSES, PREVIEW_REFERENCE_TYPES, isContentPreviewReasonCode, isContentPreviewReferenceType, isContentPreviewStatus } from '@features/chat/preview/previewReferenceContract.ts';
export { resolveAssistantMessageRoot } from '@features/chat/stream/streamDomCache.ts';
export { parseToolActivityQueryPayload } from '@features/chat/toolactivity/payloadTextParsing.ts';
export { ChatStreamRateTracker } from '@features/chat/stream/ChatStreamRateTracker.ts';
export { normalizeToolLeafName } from '@features/chat/toolactivity/toolLeafName.ts';
export { toolRunningResultIsDetailHydrated } from '@features/chat/toolactivity/toolLiveResultPolicy.ts';
export { hasToolResultInlineImageBase64, hasToolResultOmittedInlineImageBase64, resolveToolResultImageStateSignature } from '@features/chat/toolactivity/toolImageSignatures.ts';
export { compareToolResultMediaHydration, toolProjectionHasHydratedInlineMedia, toolProjectionNeedsMediaHydration, toolResultHasInlineMedia, toolResultHasOmittedInlineMedia } from '@features/chat/toolactivity/toolResultMediaHydration.ts';
export { shouldReplaceToolProjection } from '@features/chat/toolactivity/toolProjectionFreshness.ts';
export { findAssistantMessageByTimestamp, findToolProjectionByCallId, upsertToolCallProjection } from '@features/chat/toolactivity/toolProjectionMutation.ts';
export { canApplyToolCallProjectionWithoutSequenceGap } from '@features/chat/toolactivity/toolProjectionSequenceReadiness.ts';
export { ToolImageHydrationCoordinator } from '@features/chat/toolactivity/toolImageHydrationCoordinator.ts';
export { messageContainsToolDetailHydrationCandidate, messageContainsToolMediaHydrationCandidate, toolProjectionNeedsDetailHydration, toolProjectionProvidesHydratedDetails } from '@features/chat/toolactivity/toolDetailsHydrationPolicy.ts';
export type { ToolImageHydrationRequest } from '@features/chat/toolactivity/toolImageHydrationCoordinator.ts';
export { resolveToolProjectionActiveStreamingSignature, resolveToolProjectionHeaderPreviewText, resolveToolProjectionVisibleStreamingSignature, resolveToolProjectionVisibleStructureStreamingSignature } from '@features/chat/toolactivity/toolProjectionStreamingSignature.ts';
export { resolveCollapsedOverrideMap } from '@features/chat/assistanteventtimeline/timelineIndexResolution.ts';
export { mapAssistantTimelineToolPayload, mapDecodedAssistantTimelineTool } from '@features/chat/assistanteventtimeline/toolPayloadMapper.ts';
export { ChatMessageManager } from '@features/chat/message/service.ts';
export type { ChatMessageManagerDependencies } from '@features/chat/message/types.ts';
export type { ChatPostRenderRequestType } from '@features/chat/message/types.ts';
export type { ChatMessageRenderModel } from '@features/chat/message/messageRenderModel.ts';
export { applyChatMultimediaPreviewOpenActionDataset, readChatMultimediaPreviewDataset, renderChatMultimediaPreviewOpenActionAttributes, requireChatMultimediaPreviewUrl } from '@features/chat/message/multimediaPreviewDataset.ts';
export type { ChatMultimediaPreviewDataset, ChatMultimediaPreviewType } from '@features/chat/message/multimediaPreviewDataset.ts';
export { mapChatMultimediaPreviewDatasetToContentPreviewRequest } from '@features/chat/message/multimediaPreviewRequestMapper.ts';
export type { ChatMultimediaPreviewRequestHost, ChatMultimediaPreviewRequestMapping } from '@features/chat/message/multimediaPreviewRequestMapper.ts';
export { hasFolderUploadFiles, isRagDocumentAttachment, isReadyRagDocumentAttachment, normalizeFolderUploadFiles, resolveMessageTitle, resolveUploadFilesFromEvent } from '@features/chat/messageBuilding.ts';
export { optimizeCameraImageFileForVision } from '@features/chat/CameraVisionImageOptimizer.ts';
export { normalizeImageMimeTypeFromHeader } from '@features/chat/imageMimeSniffer.ts';
export { buildChatBaseRoute, buildChatConversationRoute, readConversationIdFromRouteParameters } from '@features/chat/navigation/chatRoutes.ts';
export type { ChatPageApi, ChatPreferencesManager, ChatUiParameters, ModelStreamReadiness } from '@features/chat/pagecontracts/types.ts';
export { isChatParameterControlElement, resolveChatParameterControlElement } from '@features/chat/parameters/parameterElementResolution.ts';
export type { ChatParameterControlElement } from '@features/chat/parameters/parameterElementResolution.ts';
export { ChatConversationInputsManager } from '@features/chat/conversationinputs/ChatConversationInputsManager.ts';
export { mountOptimisticInputUserMessage, resolveOptimisticInputOrderingAnchor } from '@features/chat/conversationinputs/optimisticInputUserMessage.ts';
export { ChatAttachmentProcessor } from '@features/chat/ChatAttachmentProcessor.ts';
export { ChatStorageManager } from '@features/chat/storage/service.ts';
export { serializeStorageContentPart } from '@features/chat/storage/messageNormalization.ts';
export { normalizeConversationId, requireConversationId } from '@features/chat/validation/ids.ts';
export { resolveConversationChatStreaming, resolveConversationExecutionState } from '@features/chat/conversationExecutionState.ts';
export type { ConversationExecutionState, ConversationExecutionStatus } from '@features/chat/conversationExecutionState.ts';
export { KnowledgeTerminalNotificationRegistry, selectLatestKnowledgeAttachmentSummary } from '@features/chat/knowledgeAttachmentPresentation.ts';
export type { ChatParameters, Conversation, LoadConversationMessagesOptions } from '@features/chat/storage/storageModels.ts';
export { preflightChatExecutionModelSelection, preflightChatExecutionModels } from '@features/chat/modelExecutionPreflight.ts';
export { applyChatExecutionModelStateToConversation, applyPrimaryChatExecutionModelToConversation, normalizeChatExecutionModelId, requireChatExecutionModelPreflight, requireNoActiveConversationExecution, resolvePrimaryModelIdForExecution } from '@features/chat/modelExecutionPreflight.ts';
export { showChatExecutionModelPreflightBlockedError } from '@features/chat/modelExecutionPreflight.ts';
export { ChatExecutionModelPreflightBlockedError } from '@features/chat/modelExecutionPreflight.ts';
export type { ChatExecutionModelPlan, ChatExecutionModelPreflightResult, ChatExecutionModelPreflightBlockReason } from '@features/chat/modelExecutionPreflight.ts';
export { captureConversationMutationSnapshot, restoreConversationMutationSnapshot } from '@features/chat/execution/conversationMutationSnapshot.ts';
export type { ConversationMutationSnapshot } from '@features/chat/execution/conversationMutationSnapshot.ts';
export { ChatStreamingController } from '@features/chat/chatstreamservice/controller/ChatStreamingController.ts';
export type { ChatStreamingControllerDependencies } from '@features/chat/chatstreamservice/controller/ChatStreamingController.ts';
export { isConversationStreamingUiActive } from '@features/chat/chatstreamservice/controller/state.ts';
export type { ChatStreamLifecycle, ChatStreamResponseOptions, ChatStreamStartAdmission, ChatStreamStopOptions, ChatTurnAdmissionSnapshot, ChatTurnAdmissionStreamIdentity } from '@features/chat/chatstreamservice/types.ts';
export type { ChatStreamRenderRuntime, ChatStreamTerminalUpdate, ChatStreamingControllerContext, PendingRender } from '@features/chat/chatstreamservice/controller/types.ts';
export { createStreamingElementCache } from '@features/chat/stream/streamDomCache.ts';
export { renderStreamingMessageContent } from '@features/chat/stream/streamMessageRendering.ts';
export { resolveStreamRenderQueueKey } from '@features/chat/stream/streamRenderQueueKey.ts';
export type { ActiveStreamRenderPatchType, StreamRenderPatchType } from '@features/chat/stream/streamRenderPatchType.ts';
export { applyCollapsedActivityState, readCollapsedActivityState } from '@features/chat/stream/streamCollapsedActivityState.ts';
export { applyUserSystemPromptToModelSettings, readUserSystemPromptLockState } from '@features/chat/systemPromptLock.ts';
export { applyBackendChatPreferencesToPageState, buildBackendChatPreferencesPatch, projectBackendConversationDefaults, projectBackendMcpDefaults, projectBackendRagDefaults } from '@features/chat/backendChatPreferences.ts';
export { AGENT_PLAN_MODAL_ID, CHAT_CONFIGURATION_MODAL_ID, CHAT_MCP_DEFAULT_TOOLS_MODAL_ID } from '@features/chat/modals/constants.ts';
export { CHAT_MEMORY_PROFILE_MODAL_ID } from '@features/chat/modals/constants.ts';
export { CHAT_MEMORY_UPDATED_EVENT } from '@features/chat/modals/chatMemoryProfileModal.ts';
export { CHAT_MEMORY_PROFILE_FIRST_RUN_REGISTRATION } from '@features/chat/firstRunRegistration.ts';
export { tryExtractWaitArguments } from '@features/chat/toolactivity/payloadReaders.ts';
export { ChatToolCallOutputModal } from '@features/chat/modals/toolcalloutputmodal/service.ts';
export { openChatToolCallOutputModal } from '@features/chat/modals/toolcalloutputmodal/openToolCallOutputModal.ts';
export { createChatPageMarkupContext } from '@features/chat/modals/markup/chatPageMarkupContext.ts';
export type { ChatPageMarkupContext } from '@features/chat/modals/markup/chatPageMarkupContext.ts';
export { bindChatConfigurationModalParameterEvents } from '@features/chat/modals/events.ts';
export type { ChatConfigurationModalBindingsHost } from '@features/chat/modals/events.ts';
export { bindAvatarUploadEvents, initializeAvatarPreview } from '@features/chat/modals/avatarPreview.ts';
export { VOICE_CALL_END_ACTION, VOICE_CALL_PAUSE_ACTION } from '@features/chat/modals/voiceCallModal.ts';
