"""SoAI - Access-control enums and types for the state subsystem [backend/core/state/access.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    type AccessPolicyMatrix = dict[AccessState, frozenset[AccessAction]]

__all__ = (
    "AccessAction",
    "AccessState",
)


class AccessState(str, Enum):
    UNINITIALIZED = "UNINITIALIZED"
    ANONYMOUS = "ANONYMOUS"
    ADMIN = "ADMIN"
    STANDARD = "STANDARD"


class AccessAction(str, Enum):
    WIZARD_BOOTSTRAP = "WIZARD_BOOTSTRAP"
    AUTH_COOKIE = "AUTH_COOKIE"
    NOTIFICATIONS = "NOTIFICATIONS"
    USER_ADMIN = "USER_ADMIN"
    CONFIG_PATCH = "CONFIG_PATCH"
    TERMINAL_USE = "TERMINAL_USE"
    HW_GPU_TUNING = "HW_GPU_TUNING"
    PLUGIN_ADMIN = "PLUGIN_ADMIN"
    FACTORY_RESET = "FACTORY_RESET"
    METRICS_RESET = "METRICS_RESET"
    REQUEST_CANCELLATION_ADMIN = "REQUEST_CANCELLATION_ADMIN"
    SYSTEM_POWER = "SYSTEM_POWER"
    MODEL_READ = "MODEL_READ"
    MODEL_ADMIN = "MODEL_ADMIN"
    MODEL_ROUTING_READ = "MODEL_ROUTING_READ"
    MODEL_ROUTING_ADMIN = "MODEL_ROUTING_ADMIN"
    SOFTWARE_UPDATE = "SOFTWARE_UPDATE"
    LOG_ACCESS = "LOG_ACCESS"
    ACL_ADMIN = "ACL_ADMIN"
    SYSTEM_STATUS_READ = "SYSTEM_STATUS_READ"
    PLUGIN_READ = "PLUGIN_READ"
    HARDWARE_READ = "HARDWARE_READ"
    SEARCH_READ = "SEARCH_READ"
    OPENAI_API = "OPENAI_API"
    WEBUI_APPEARANCE_ADMIN = "WEBUI_APPEARANCE_ADMIN"
    OPENAI_API_ADMIN = "OPENAI_API_ADMIN"
    MCP_ADMIN = "MCP_ADMIN"
    TASK_MANAGEMENT = "TASK_MANAGEMENT"
    HW_PROCESS_VIEW = "HW_PROCESS_VIEW"
    BACKUP_ADMIN = "BACKUP_ADMIN"
    FILE_EXPLORER_READ = "FILE_EXPLORER_READ"
    FILE_EXPLORER_WRITE = "FILE_EXPLORER_WRITE"
    FILE_EXPLORER_HASH = "FILE_EXPLORER_HASH"
    FILE_EXPLORER_ADMIN = "FILE_EXPLORER_ADMIN"
    HOST_MANAGEMENT_ADMIN = "HOST_MANAGEMENT_ADMIN"
    WEB_SEARCH = "WEB_SEARCH"
    RAG_USE = "RAG_USE"
    MCP_USE = "MCP_USE"
    LICENSING_ADMIN = "LICENSING_ADMIN"
    RECOVERY_ADMIN = "RECOVERY_ADMIN"
