"""SoAI - Orchestrator runtime state transition mapping [backend/core/state/orchestrator_state_transitions.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from typing import TYPE_CHECKING

from core.state.state_names import (
    ORCH_STATE_DISABLED,
    ORCH_STATE_ERROR,
    ORCH_STATE_IDLE,
    ORCH_STATE_LOADING,
    ORCH_STATE_PROCESSING,
    ORCH_STATE_QUARANTINED,
    ORCH_STATE_READY,
    ORCH_STATE_READY_DIRTY,
    ORCH_STATE_READY_PENDING_DISPATCH,
    ORCH_STATE_STARTING,
    ORCH_STATE_STOPPED,
    ORCH_STATE_STOPPING,
    ORCH_STATE_UNKNOWN,
    PLUGIN_STATE_BACKEND_INSTALLING,
    PLUGIN_STATE_BACKEND_NOT_INSTALLED,
    PLUGIN_STATE_BACKEND_UNINSTALL_ERROR,
    PLUGIN_STATE_BACKEND_UPDATING,
    PLUGIN_STATE_DELETE_ERROR,
    PLUGIN_STATE_DELETING,
    PLUGIN_STATE_INCOMPATIBLE,
    PLUGIN_STATE_INSTALL_ERROR,
    PLUGIN_STATE_LOAD_ERROR,
    PLUGIN_STATE_PERSISTENT_READY,
    PLUGIN_STATE_REMOVING_BACKEND,
    PLUGIN_STATE_STOPPED,
    PLUGIN_STATE_UPDATE_ERROR,
)

if TYPE_CHECKING:
    from core.state.state_names import PluginRuntimeStateName

__all__ = ("ORCHESTRATOR_STATE_TRANSITIONS",)

ORCHESTRATOR_STATE_TRANSITIONS: tuple[
    tuple[PluginRuntimeStateName, tuple[PluginRuntimeStateName, ...]],
    ...,
] = (
    (
        ORCH_STATE_STARTING,
        (
            ORCH_STATE_LOADING,
            ORCH_STATE_IDLE,
            ORCH_STATE_ERROR,
            ORCH_STATE_STOPPED,
            ORCH_STATE_STOPPING,
            ORCH_STATE_DISABLED,
        ),
    ),
    (
        ORCH_STATE_LOADING,
        (
            ORCH_STATE_READY_PENDING_DISPATCH,
            ORCH_STATE_ERROR,
            ORCH_STATE_STOPPED,
            ORCH_STATE_STOPPING,
            ORCH_STATE_DISABLED,
        ),
    ),
    (
        ORCH_STATE_READY_PENDING_DISPATCH,
        (
            ORCH_STATE_PROCESSING,
            ORCH_STATE_STOPPING,
            ORCH_STATE_ERROR,
            ORCH_STATE_LOADING,
            ORCH_STATE_READY_DIRTY,
            ORCH_STATE_READY,
            ORCH_STATE_DISABLED,
        ),
    ),
    (
        ORCH_STATE_READY,
        (
            ORCH_STATE_LOADING,
            ORCH_STATE_PROCESSING,
            ORCH_STATE_STOPPING,
            ORCH_STATE_ERROR,
            ORCH_STATE_READY_DIRTY,
            ORCH_STATE_IDLE,
            PLUGIN_STATE_DELETING,
            ORCH_STATE_DISABLED,
            ORCH_STATE_STOPPED,
        ),
    ),
    (
        ORCH_STATE_READY_DIRTY,
        (
            ORCH_STATE_LOADING,
            ORCH_STATE_PROCESSING,
            ORCH_STATE_STOPPING,
            ORCH_STATE_ERROR,
            ORCH_STATE_READY,
            PLUGIN_STATE_DELETING,
            ORCH_STATE_DISABLED,
            ORCH_STATE_STOPPED,
        ),
    ),
    (
        ORCH_STATE_PROCESSING,
        (
            ORCH_STATE_READY,
            ORCH_STATE_READY_DIRTY,
            ORCH_STATE_ERROR,
            ORCH_STATE_STOPPING,
            ORCH_STATE_DISABLED,
            PLUGIN_STATE_PERSISTENT_READY,
        ),
    ),
    (
        ORCH_STATE_STOPPING,
        (
            ORCH_STATE_STOPPED,
            ORCH_STATE_ERROR,
            ORCH_STATE_DISABLED,
        ),
    ),
    (
        ORCH_STATE_ERROR,
        (
            ORCH_STATE_STARTING,
            ORCH_STATE_STOPPED,
            ORCH_STATE_STOPPING,
            ORCH_STATE_READY,
            ORCH_STATE_QUARANTINED,
            PLUGIN_STATE_BACKEND_NOT_INSTALLED,
            PLUGIN_STATE_DELETING,
            ORCH_STATE_DISABLED,
            PLUGIN_STATE_PERSISTENT_READY,
        ),
    ),
    (
        ORCH_STATE_IDLE,
        (
            ORCH_STATE_LOADING,
            ORCH_STATE_STOPPING,
            ORCH_STATE_ERROR,
            PLUGIN_STATE_DELETING,
            ORCH_STATE_DISABLED,
        ),
    ),
    (
        ORCH_STATE_QUARANTINED,
        (
            ORCH_STATE_STOPPING,
            ORCH_STATE_STOPPED,
            ORCH_STATE_DISABLED,
            PLUGIN_STATE_DELETING,
            PLUGIN_STATE_PERSISTENT_READY,
            PLUGIN_STATE_BACKEND_NOT_INSTALLED,
            PLUGIN_STATE_INCOMPATIBLE,
        ),
    ),
    (
        ORCH_STATE_STOPPED,
        (
            ORCH_STATE_STARTING,
            ORCH_STATE_DISABLED,
            ORCH_STATE_ERROR,
            ORCH_STATE_QUARANTINED,
            PLUGIN_STATE_DELETING,
            PLUGIN_STATE_REMOVING_BACKEND,
            PLUGIN_STATE_BACKEND_INSTALLING,
            PLUGIN_STATE_BACKEND_UPDATING,
            PLUGIN_STATE_BACKEND_NOT_INSTALLED,
            PLUGIN_STATE_PERSISTENT_READY,
            PLUGIN_STATE_INSTALL_ERROR,
            PLUGIN_STATE_LOAD_ERROR,
            PLUGIN_STATE_UPDATE_ERROR,
            PLUGIN_STATE_BACKEND_UNINSTALL_ERROR,
            PLUGIN_STATE_DELETE_ERROR,
            PLUGIN_STATE_INCOMPATIBLE,
        ),
    ),
    (
        ORCH_STATE_DISABLED,
        (
            PLUGIN_STATE_STOPPED,
            PLUGIN_STATE_DELETING,
            PLUGIN_STATE_REMOVING_BACKEND,
            ORCH_STATE_ERROR,
            PLUGIN_STATE_BACKEND_NOT_INSTALLED,
            PLUGIN_STATE_PERSISTENT_READY,
        ),
    ),
    (
        ORCH_STATE_UNKNOWN,
        (
            ORCH_STATE_STARTING,
            ORCH_STATE_STOPPED,
            ORCH_STATE_ERROR,
            ORCH_STATE_READY,
            ORCH_STATE_IDLE,
            ORCH_STATE_READY_DIRTY,
            ORCH_STATE_READY_PENDING_DISPATCH,
        ),
    ),
)
