"""SoAI - Derived state set constants [backend/core/state/state_transition_sets.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

from typing import TYPE_CHECKING

from core.state.state_names import (
    ORCH_STATE_DISABLED,
    ORCH_STATE_ERROR,
    ORCH_STATE_IDLE,
    ORCH_STATE_LOADING,
    ORCH_STATE_PROCESSING,
    ORCH_STATE_QUARANTINED,
    ORCH_STATE_READY,
    ORCH_STATE_READY_DIRTY,
    ORCH_STATE_READY_PENDING_DISPATCH,
    ORCH_STATE_STARTING,
    ORCH_STATE_STOPPED,
    ORCH_STATE_STOPPING,
    ORCHESTRATOR_STATE_NAMES,
    PLUGIN_STATE_ABSENT,
    PLUGIN_STATE_BACKEND_INSTALLING,
    PLUGIN_STATE_BACKEND_NOT_INSTALLED,
    PLUGIN_STATE_BACKEND_UNINSTALL_ERROR,
    PLUGIN_STATE_BACKEND_UPDATING,
    PLUGIN_STATE_DELETE_ERROR,
    PLUGIN_STATE_DELETING,
    PLUGIN_STATE_INCOMPATIBLE,
    PLUGIN_STATE_INSTALL_ERROR,
    PLUGIN_STATE_LOAD_ERROR,
    PLUGIN_STATE_NOT_DETECTED,
    PLUGIN_STATE_PERSISTENT_READY,
    PLUGIN_STATE_REMOVING_BACKEND,
    PLUGIN_STATE_STOPPED,
    PLUGIN_STATE_UPDATE_ERROR,
)

if TYPE_CHECKING:
    from core.state.state_names import (
        OrchestratorStateName,
        PluginRuntimeStateName,
        PluginStateName,
    )

__all__ = ()

ORCHESTRATOR_STATES: frozenset[OrchestratorStateName] = frozenset((*ORCHESTRATOR_STATE_NAMES,))

LOADED_ORCHESTRATOR_STATES = frozenset(
    {
        ORCH_STATE_LOADING,
        ORCH_STATE_READY,
        ORCH_STATE_READY_DIRTY,
        ORCH_STATE_READY_PENDING_DISPATCH,
        ORCH_STATE_PROCESSING,
    },
)
ACTIVE_RESOURCE_STATES = frozenset(
    {
        ORCH_STATE_LOADING,
        ORCH_STATE_IDLE,
        ORCH_STATE_READY_PENDING_DISPATCH,
        ORCH_STATE_READY,
        ORCH_STATE_READY_DIRTY,
        ORCH_STATE_PROCESSING,
        ORCH_STATE_ERROR,
        ORCH_STATE_QUARANTINED,
    },
)
PLUGIN_MANAGER_TRANSIENT_STATES: frozenset[PluginStateName] = frozenset(
    (
        PLUGIN_STATE_BACKEND_INSTALLING,
        PLUGIN_STATE_BACKEND_UPDATING,
        PLUGIN_STATE_REMOVING_BACKEND,
        PLUGIN_STATE_DELETING,
    ),
)
OPERATIONAL_ERROR_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        PLUGIN_STATE_INSTALL_ERROR,
        PLUGIN_STATE_LOAD_ERROR,
        PLUGIN_STATE_UPDATE_ERROR,
        PLUGIN_STATE_BACKEND_UNINSTALL_ERROR,
        PLUGIN_STATE_DELETE_ERROR,
    ),
)
ALL_TRANSIENT_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        ORCH_STATE_STARTING,
        ORCH_STATE_LOADING,
        ORCH_STATE_STOPPING,
        ORCH_STATE_READY_PENDING_DISPATCH,
        PLUGIN_STATE_BACKEND_INSTALLING,
        PLUGIN_STATE_BACKEND_UPDATING,
        PLUGIN_STATE_REMOVING_BACKEND,
        PLUGIN_STATE_DELETING,
    ),
)
UNAVAILABLE_PLUGIN_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    {
        ORCH_STATE_DISABLED,
        ORCH_STATE_QUARANTINED,
        PLUGIN_STATE_BACKEND_NOT_INSTALLED,
        PLUGIN_STATE_NOT_DETECTED,
        PLUGIN_STATE_ABSENT,
        PLUGIN_STATE_DELETING,
        PLUGIN_STATE_INSTALL_ERROR,
        PLUGIN_STATE_LOAD_ERROR,
        PLUGIN_STATE_UPDATE_ERROR,
        PLUGIN_STATE_BACKEND_UNINSTALL_ERROR,
        PLUGIN_STATE_DELETE_ERROR,
        PLUGIN_STATE_INCOMPATIBLE,
        PLUGIN_STATE_BACKEND_INSTALLING,
        PLUGIN_STATE_BACKEND_UPDATING,
        PLUGIN_STATE_REMOVING_BACKEND,
    },
)
SCHEDULER_DEFERRED_PLUGIN_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        ORCH_STATE_ERROR,
        ORCH_STATE_QUARANTINED,
    ),
)
SCHEDULER_UNAVAILABLE_PLUGIN_STATES: frozenset[PluginRuntimeStateName] = (
    UNAVAILABLE_PLUGIN_STATES - SCHEDULER_DEFERRED_PLUGIN_STATES
)
SCHEDULER_INACTIVE_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        ORCH_STATE_STOPPED,
        PLUGIN_STATE_STOPPED,
        ORCH_STATE_DISABLED,
        PLUGIN_STATE_BACKEND_NOT_INSTALLED,
        PLUGIN_STATE_INSTALL_ERROR,
        PLUGIN_STATE_LOAD_ERROR,
        PLUGIN_STATE_UPDATE_ERROR,
        PLUGIN_STATE_BACKEND_UNINSTALL_ERROR,
        PLUGIN_STATE_DELETE_ERROR,
        PLUGIN_STATE_NOT_DETECTED,
        PLUGIN_STATE_INCOMPATIBLE,
        PLUGIN_STATE_BACKEND_INSTALLING,
        PLUGIN_STATE_BACKEND_UPDATING,
        PLUGIN_STATE_REMOVING_BACKEND,
        PLUGIN_STATE_DELETING,
    ),
)
PLUGIN_DISCOVERY_SKIP_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        PLUGIN_STATE_BACKEND_NOT_INSTALLED,
        PLUGIN_STATE_INSTALL_ERROR,
        PLUGIN_STATE_LOAD_ERROR,
        PLUGIN_STATE_UPDATE_ERROR,
        PLUGIN_STATE_BACKEND_UNINSTALL_ERROR,
        PLUGIN_STATE_DELETE_ERROR,
        PLUGIN_STATE_NOT_DETECTED,
        PLUGIN_STATE_REMOVING_BACKEND,
        PLUGIN_STATE_BACKEND_INSTALLING,
        PLUGIN_STATE_BACKEND_UPDATING,
        PLUGIN_STATE_DELETING,
        PLUGIN_STATE_INCOMPATIBLE,
    ),
)
ELIGIBILITY_PROHIBITIVE_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        ORCH_STATE_DISABLED,
        ORCH_STATE_QUARANTINED,
        ORCH_STATE_ERROR,
        PLUGIN_STATE_DELETING,
        PLUGIN_STATE_REMOVING_BACKEND,
        PLUGIN_STATE_INCOMPATIBLE,
        PLUGIN_STATE_BACKEND_INSTALLING,
        PLUGIN_STATE_BACKEND_UPDATING,
    ),
)
STOP_PROHIBITIVE_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        ORCH_STATE_STOPPING,
        PLUGIN_STATE_STOPPED,
        ORCH_STATE_STOPPED,
        ORCH_STATE_DISABLED,
        PLUGIN_STATE_INCOMPATIBLE,
        PLUGIN_STATE_BACKEND_INSTALLING,
        PLUGIN_STATE_BACKEND_UPDATING,
        PLUGIN_STATE_REMOVING_BACKEND,
        PLUGIN_STATE_DELETING,
    ),
)
NON_STOPPABLE_STATES = frozenset(
    {
        ORCH_STATE_STOPPED,
        PLUGIN_STATE_STOPPED,
        ORCH_STATE_DISABLED,
        PLUGIN_STATE_BACKEND_NOT_INSTALLED,
        PLUGIN_STATE_NOT_DETECTED,
        PLUGIN_STATE_DELETING,
        PLUGIN_STATE_REMOVING_BACKEND,
        PLUGIN_STATE_INCOMPATIBLE,
        PLUGIN_STATE_BACKEND_UPDATING,
    },
)
INTERRUPTIBLE_IDLE_STATES: frozenset[OrchestratorStateName] = frozenset(
    (ORCH_STATE_IDLE, ORCH_STATE_READY, ORCH_STATE_READY_DIRTY),
)
RUNTIME_TERMINATED_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        PLUGIN_STATE_STOPPED,
        PLUGIN_STATE_BACKEND_NOT_INSTALLED,
        PLUGIN_STATE_NOT_DETECTED,
        PLUGIN_STATE_ABSENT,
        ORCH_STATE_STOPPED,
    ),
)
DISPATCH_READY_STATES: frozenset[PluginRuntimeStateName] = frozenset(
    (
        ORCH_STATE_READY,
        ORCH_STATE_READY_PENDING_DISPATCH,
        ORCH_STATE_PROCESSING,
        PLUGIN_STATE_PERSISTENT_READY,
    ),
)
