/* SoAI - Settings feature action IDs [frontend/assets/ts/features/settings/externalaccounts/actionIds.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

import { createActionIdSet } from '@core/dom/actions/actionIdGuard.ts';

const EXTERNAL_ACCOUNTS_ACTION_ADD = 'settings.externalAccounts.add';
const EXTERNAL_ACCOUNTS_ACTION_MANAGE = 'settings.externalAccounts.manage';
const EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_MAIL = 'settings.externalAccounts.modal.chooseMail';
const EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_CALENDAR = 'settings.externalAccounts.modal.chooseCalendar';
const EXTERNAL_ACCOUNT_MODAL_ACTION_BACK = 'settings.externalAccounts.modal.back';
const EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CONNECT = 'settings.externalAccounts.modal.oauthConnect';
const EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CLEAR = 'settings.externalAccounts.modal.oauthClear';
const EXTERNAL_ACCOUNT_MODAL_ACTION_DELETE = 'settings.externalAccounts.modal.delete';
const EXTERNAL_ACCOUNT_MODAL_ACTION_TEST = 'settings.externalAccounts.modal.test';
const EXTERNAL_ACCOUNT_MODAL_ACTION_SYNC = 'settings.externalAccounts.modal.sync';
const EXTERNAL_ACCOUNT_MODAL_ACTION_SAVE = 'settings.externalAccounts.modal.save';

type ExternalAccountsActionId = typeof EXTERNAL_ACCOUNTS_ACTION_ADD | typeof EXTERNAL_ACCOUNTS_ACTION_MANAGE;
type ExternalAccountModalActionId = typeof EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_MAIL | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_CALENDAR | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_BACK | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CONNECT | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CLEAR | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_DELETE | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_TEST | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_SYNC | typeof EXTERNAL_ACCOUNT_MODAL_ACTION_SAVE;

const { guard: isExternalAccountsActionId } = createActionIdSet(EXTERNAL_ACCOUNTS_ACTION_ADD, EXTERNAL_ACCOUNTS_ACTION_MANAGE);
const { guard: isExternalAccountModalActionId } = createActionIdSet(EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_MAIL, EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_CALENDAR, EXTERNAL_ACCOUNT_MODAL_ACTION_BACK, EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CONNECT, EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CLEAR, EXTERNAL_ACCOUNT_MODAL_ACTION_DELETE, EXTERNAL_ACCOUNT_MODAL_ACTION_TEST, EXTERNAL_ACCOUNT_MODAL_ACTION_SYNC, EXTERNAL_ACCOUNT_MODAL_ACTION_SAVE);

export { EXTERNAL_ACCOUNTS_ACTION_ADD, EXTERNAL_ACCOUNTS_ACTION_MANAGE, EXTERNAL_ACCOUNT_MODAL_ACTION_BACK, EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_CALENDAR, EXTERNAL_ACCOUNT_MODAL_ACTION_CHOOSE_MAIL, EXTERNAL_ACCOUNT_MODAL_ACTION_DELETE, EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CLEAR, EXTERNAL_ACCOUNT_MODAL_ACTION_OAUTH_CONNECT, EXTERNAL_ACCOUNT_MODAL_ACTION_SAVE, EXTERNAL_ACCOUNT_MODAL_ACTION_SYNC, EXTERNAL_ACCOUNT_MODAL_ACTION_TEST, isExternalAccountModalActionId, isExternalAccountsActionId };
export type { ExternalAccountModalActionId, ExternalAccountsActionId };
