/* SoAI - Plugins feature plugin action IDs [frontend/assets/ts/features/plugins/contracts/pluginActionIds.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

const PLUGINS_ACTION_DOWNLOAD_PLUGIN = 'download-plugin';
const PLUGINS_ACTION_STOP_ALL = 'stop-all-plugins';
const PLUGINS_ACTION_OPEN_CONCURRENT = 'open-concurrent-plugins';
const PLUGINS_ACTION_DELETE_PLUGIN = 'delete';
const PLUGINS_ACTION_EDIT_CONFIG = 'edit-config';
const PLUGINS_ACTION_OPEN_PLUGIN = 'open-plugin';
const PLUGINS_ACTION_ENABLE_OVERRIDE = 'enable-override';
const PLUGINS_ACTION_DISABLE_OVERRIDE = 'disable-override';
const PLUGINS_ACTION_TOGGLE_ENABLED = 'toggle-enabled';
const PLUGINS_ACTION_STOP_PLUGIN = 'stop-plugin';
const PLUGINS_ACTION_INSTALL_BACKEND = 'install-backend';
const PLUGINS_ACTION_MANAGE_BACKEND = 'manage-backend';
const PLUGINS_ACTION_CLONE_PLUGIN = 'clone';
const PLUGINS_ACTION_METRIC_BADGE = 'plugins.metricBadge';
const PLUGINS_ACTION_DOWNLOAD_CHOOSE_FILE = 'plugins.download.chooseFile';
const PLUGINS_ACTION_DOWNLOAD_CONFIRM = 'plugins.download.confirm';
const PLUGINS_ACTION_DOWNLOAD_URL_TAB = 'plugins.download.urlTab';
const PLUGINS_ACTION_DOWNLOAD_FILE_TAB = 'plugins.download.fileTab';
const PLUGINS_ACTION_DOWNLOAD_MANUAL_TAB = 'plugins.download.manualTab';
const PLUGINS_ACTION_DOWNLOAD_MANUAL_COPY_PATH = 'plugins.download.manual.copyPath';
const PLUGINS_ACTION_DOWNLOAD_MANUAL_OPEN_FILE_EXPLORER = 'plugins.download.manual.openFileExplorer';
const PLUGINS_ACTION_DOWNLOAD_MANUAL_RESTART = 'plugins.download.manual.restart';
const PLUGINS_ACTION_CONFIG_SAVE = 'plugins.config.save';
const PLUGINS_ACTION_INFO_COPY = 'plugins.info.copy';
const PLUGINS_ACTION_BACKEND_INSTALL_START = 'plugins.backend.install.start';
const PLUGINS_ACTION_BACKEND_UPDATE_CHECK = 'plugins.backend.update.check';
const PLUGINS_ACTION_BACKEND_UNINSTALL = 'plugins.backend.uninstall';
const PLUGINS_ACTION_CONCURRENT_SAVE = 'plugins.concurrent.save';
const PLUGINS_ACTION_CLONE_START = 'plugins.clone.start';
const PLUGINS_ACTION_DOWNLOAD_URL_INPUT = 'plugins.download.urlInput';
const PLUGINS_ACTION_CONCURRENT_SLIDER_INPUT = 'plugins.concurrent.sliderInput';
const PLUGINS_ACTION_CONCURRENT_VALUE_INPUT = 'plugins.concurrent.valueInput';
const PLUGINS_ACTION_DOWNLOAD_FILE_CHANGE = 'plugins.download.fileChange';

export {
    PLUGINS_ACTION_BACKEND_INSTALL_START,
    PLUGINS_ACTION_BACKEND_UNINSTALL,
    PLUGINS_ACTION_BACKEND_UPDATE_CHECK,
    PLUGINS_ACTION_CLONE_PLUGIN,
    PLUGINS_ACTION_CLONE_START,
    PLUGINS_ACTION_CONCURRENT_SAVE,
    PLUGINS_ACTION_CONCURRENT_SLIDER_INPUT,
    PLUGINS_ACTION_CONCURRENT_VALUE_INPUT,
    PLUGINS_ACTION_CONFIG_SAVE,
    PLUGINS_ACTION_DELETE_PLUGIN,
    PLUGINS_ACTION_DISABLE_OVERRIDE,
    PLUGINS_ACTION_DOWNLOAD_CHOOSE_FILE,
    PLUGINS_ACTION_DOWNLOAD_CONFIRM,
    PLUGINS_ACTION_DOWNLOAD_FILE_CHANGE,
    PLUGINS_ACTION_DOWNLOAD_FILE_TAB,
    PLUGINS_ACTION_DOWNLOAD_MANUAL_COPY_PATH,
    PLUGINS_ACTION_DOWNLOAD_MANUAL_OPEN_FILE_EXPLORER,
    PLUGINS_ACTION_DOWNLOAD_MANUAL_RESTART,
    PLUGINS_ACTION_DOWNLOAD_MANUAL_TAB,
    PLUGINS_ACTION_DOWNLOAD_PLUGIN,
    PLUGINS_ACTION_DOWNLOAD_URL_INPUT,
    PLUGINS_ACTION_DOWNLOAD_URL_TAB,
    PLUGINS_ACTION_EDIT_CONFIG,
    PLUGINS_ACTION_ENABLE_OVERRIDE,
    PLUGINS_ACTION_INFO_COPY,
    PLUGINS_ACTION_INSTALL_BACKEND,
    PLUGINS_ACTION_MANAGE_BACKEND,
    PLUGINS_ACTION_METRIC_BADGE,
    PLUGINS_ACTION_OPEN_CONCURRENT,
    PLUGINS_ACTION_OPEN_PLUGIN,
    PLUGINS_ACTION_STOP_ALL,
    PLUGINS_ACTION_STOP_PLUGIN,
    PLUGINS_ACTION_TOGGLE_ENABLED
};
