"""SoAI - Shared audit event constants [backend/core/audit/constants.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = ()

AUDIT_BACKUP_LIST = "LIST_BACKUPS"
AUDIT_BACKUP_CREATE = "CREATE_BACKUP"
AUDIT_BACKUP_RESTORE = "RESTORE_BACKUP"
AUDIT_BACKUP_DELETE = "DELETE_BACKUP"
AUDIT_BACKUP_VERIFY = "VERIFY_BACKUP"
AUDIT_BACKUP_EXPORT = "EXPORT_BACKUP"

AUDIT_FILE_EXPLORER_LIST = "FILE_EXPLORER_LIST"
AUDIT_FILE_EXPLORER_READ = "FILE_EXPLORER_READ"
AUDIT_FILE_EXPLORER_BATCH_METADATA = "FILE_EXPLORER_BATCH_METADATA"
AUDIT_FILE_EXPLORER_WRITE = "FILE_EXPLORER_WRITE"
AUDIT_FILE_EXPLORER_DELETE = "FILE_EXPLORER_DELETE"
AUDIT_FILE_EXPLORER_MOVE = "FILE_EXPLORER_MOVE"
AUDIT_FILE_EXPLORER_COPY = "FILE_EXPLORER_COPY"
AUDIT_FILE_EXPLORER_MKDIR = "FILE_EXPLORER_MKDIR"
AUDIT_FILE_EXPLORER_UPLOAD = "FILE_EXPLORER_UPLOAD"
AUDIT_FILE_EXPLORER_DOWNLOAD = "FILE_EXPLORER_DOWNLOAD"
AUDIT_FILE_EXPLORER_SEARCH = "FILE_EXPLORER_SEARCH"
