"""SoAI - Binary game/ROM extension constants [backend/core/files/extensions/binaries_extensions_games_and_roms.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = ()

BINARY_EXTENSIONS_GAMES_AND_ROMS = frozenset(
    (
        "32x",
        "3ds",
        "a26",
        "a52",
        "a78",
        "a7800",
        "atr",
        "atx",
        "bsp",
        "cdi",
        "chd",
        "cia",
        "col",
        "cso",
        "dol",
        "fds",
        "fd",
        "fla",
        "gb",
        "gba",
        "gbc",
        "gcf",
        "gcm",
        "gdb",
        "gdi",
        "gen",
        "gg",
        "int",
        "lnx",
        "mpq",
        "n64",
        "ndd",
        "nds",
        "nes",
        "ngc",
        "ngp",
        "nro",
        "nso",
        "nsp",
        "nsf",
        "pak",
        "pce",
        "pbp",
        "pk3",
        "pk4",
        "ps2",
        "ps3",
        "psx",
        "pup",
        "rom",
        "sav",
        "saver",
        "sfc",
        "sg",
        "sgx",
        "smc",
        "smd",
        "sms",
        "snes",
        "sram",
        "srm",
        "sv",
        "u",
        "unity3d",
        "v64",
        "vboy",
        "vdf",
        "vpk",
        "wad",
        "wbfs",
        "xbe",
        "xci",
        "xex",
        "xiso",
        "z64",
    ),
)
