"""SoAI - Binary design/CAD/font extension constants [backend/core/files/extensions/binaries_extensions_design_and_fonts.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = ()

BINARY_EXTENSIONS_DESIGN_AND_FONTS = frozenset(
    (
        "3mf",
        "afdesign",
        "afm",
        "afphoto",
        "afpub",
        "ai",
        "amf",
        "ani",
        "blend",
        "catpart",
        "catproduct",
        "cur",
        "dae",
        "dfont",
        "dwg",
        "dxf",
        "emf",
        "eot",
        "eps",
        "exp",
        "f3d",
        "fnt",
        "fon",
        "iges",
        "igs",
        "iam",
        "indd",
        "ipt",
        "kra",
        "ma",
        "mb",
        "otf",
        "ora",
        "pfb",
        "pfm",
        "sldasm",
        "sldprt",
        "skp",
        "step",
        "stl",
        "stp",
        "ttc",
        "ttf",
        "vec",
        "wmf",
        "woff",
        "woff2",
        "x3d",
        "xcf",
    ),
)
