"""SoAI - Plugin manifest class field contract [backend/plugins/manifest/class_field_contract.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = (
    "PLUGIN_FIELD_ALIASES",
    "PLUGIN_FIELD_AUTHOR_SOAIPLUGIN",
    "PLUGIN_FIELD_BACKEND_VARIANT_OPTIONS",
    "PLUGIN_FIELD_CLONABLE_FIELDS",
    "PLUGIN_FIELD_DEFAULT_CONFIGURATION",
    "PLUGIN_FIELD_DESCRIPTION_SOAIPLUGIN",
    "PLUGIN_FIELD_EXTERNAL_PROVIDER_DEFAULTS",
    "PLUGIN_FIELD_EXTERNAL_PROVIDER_MODE",
    "PLUGIN_FIELD_LOCAL_MODELS",
    "PLUGIN_FIELD_LOCAL_RESOURCES",
    "PLUGIN_FIELD_LICENSE_MANAGED_BACKEND",
    "PLUGIN_FIELD_LICENSE_SOAIPLUGIN",
    "PLUGIN_FIELD_MAX_CONCURRENT_REQUESTS",
    "PLUGIN_FIELD_MODEL_REPOSITORY",
    "PLUGIN_FIELD_MODEL_TYPES",
    "PLUGIN_FIELD_NAME",
    "PLUGIN_FIELD_PACKAGE_DEPENDENCIES",
    "PLUGIN_FIELD_PERSISTENT",
    "PLUGIN_FIELD_PLUGIN_DEPENDENCIES",
    "PLUGIN_FIELD_REQUIRED_SOAI_VERSION",
    "PLUGIN_FIELD_REQUIRED_SYSTEM_CAPABILITIES",
    "PLUGIN_FIELD_SUPPORTED_MODALITIES",
    "PLUGIN_FIELD_SUPPORTS_BACKEND_INSTALLATION",
    "PLUGIN_FIELD_SUPPORTS_BACKEND_PROCESS_TRACKING",
    "PLUGIN_FIELD_SUPPORTS_CLONING",
    "PLUGIN_FIELD_SUPPORTS_CONFIGURATION",
    "PLUGIN_FIELD_SUPPORTS_EXTERNAL_PROVIDERS",
    "PLUGIN_FIELD_SUPPORTS_GPU_BINDING",
    "PLUGIN_FIELD_SUPPORTS_MODEL_DELETION",
    "PLUGIN_FIELD_SUPPORTS_MODEL_DOWNLOAD",
    "PLUGIN_FIELD_SUPPORTS_MODEL_SEARCH",
    "PLUGIN_FIELD_SUPPORTS_MODEL_VARIANT_DISCOVERY",
    "PLUGIN_FIELD_SUPPORTS_PROMPT_TOKEN_COUNTING",
    "PLUGIN_FIELD_VERSION_SOAIPLUGIN",
    "PLUGIN_FIELD_WEBSITE_BACKEND",
    "PLUGIN_FIELD_WEBSITE_SOAIPLUGIN",
    "PLUGIN_FIELD_WELCOME_MESSAGE",
    "PLUGIN_REQUIRED_METADATA_FIELDS",
)

PLUGIN_FIELD_NAME = "NAME"
PLUGIN_FIELD_AUTHOR_SOAIPLUGIN = "AUTHOR_SOAIPLUGIN"
PLUGIN_FIELD_DESCRIPTION_SOAIPLUGIN = "DESCRIPTION_SOAIPLUGIN"
PLUGIN_FIELD_WEBSITE_SOAIPLUGIN = "WEBSITE_SOAIPLUGIN"
PLUGIN_FIELD_VERSION_SOAIPLUGIN = "VERSION_SOAIPLUGIN"
PLUGIN_FIELD_LICENSE_SOAIPLUGIN = "LICENSE_SOAIPLUGIN"
PLUGIN_FIELD_REQUIRED_SOAI_VERSION = "REQUIRED_SOAI_VERSION"
PLUGIN_FIELD_MODEL_REPOSITORY = "MODEL_REPOSITORY"
PLUGIN_FIELD_MODEL_TYPES = "MODEL_TYPES"
PLUGIN_FIELD_WEBSITE_BACKEND = "WEBSITE_BACKEND"
PLUGIN_FIELD_LICENSE_MANAGED_BACKEND = "LICENSE_MANAGED_BACKEND"
PLUGIN_FIELD_MAX_CONCURRENT_REQUESTS = "MAX_CONCURRENT_REQUESTS"
PLUGIN_FIELD_REQUIRED_SYSTEM_CAPABILITIES = "REQUIRED_SYSTEM_CAPABILITIES"
PLUGIN_FIELD_DEFAULT_CONFIGURATION = "DEFAULT_CONFIGURATION"
PLUGIN_FIELD_ALIASES = "ALIASES"
PLUGIN_FIELD_BACKEND_VARIANT_OPTIONS = "BACKEND_VARIANT_OPTIONS"
PLUGIN_FIELD_LOCAL_RESOURCES = "LOCAL_RESOURCES"
PLUGIN_FIELD_LOCAL_MODELS = "LOCAL_MODELS"
PLUGIN_FIELD_PERSISTENT = "PERSISTENT"
PLUGIN_FIELD_SUPPORTS_BACKEND_INSTALLATION = "SUPPORTS_BACKEND_INSTALLATION"
PLUGIN_FIELD_SUPPORTS_BACKEND_PROCESS_TRACKING = "SUPPORTS_BACKEND_PROCESS_TRACKING"
PLUGIN_FIELD_SUPPORTS_CONFIGURATION = "SUPPORTS_CONFIGURATION"
PLUGIN_FIELD_SUPPORTS_GPU_BINDING = "SUPPORTS_GPU_BINDING"
PLUGIN_FIELD_SUPPORTS_MODEL_VARIANT_DISCOVERY = "SUPPORTS_MODEL_VARIANT_DISCOVERY"
PLUGIN_FIELD_SUPPORTS_MODEL_DELETION = "SUPPORTS_MODEL_DELETION"
PLUGIN_FIELD_SUPPORTS_MODEL_DOWNLOAD = "SUPPORTS_MODEL_DOWNLOAD"
PLUGIN_FIELD_SUPPORTS_MODEL_SEARCH = "SUPPORTS_MODEL_SEARCH"
PLUGIN_FIELD_SUPPORTS_CLONING = "SUPPORTS_CLONING"
PLUGIN_FIELD_SUPPORTS_EXTERNAL_PROVIDERS = "SUPPORTS_EXTERNAL_PROVIDERS"
PLUGIN_FIELD_SUPPORTS_PROMPT_TOKEN_COUNTING = "SUPPORTS_PROMPT_TOKEN_COUNTING"
PLUGIN_FIELD_EXTERNAL_PROVIDER_MODE = "EXTERNAL_PROVIDER_MODE"
PLUGIN_FIELD_EXTERNAL_PROVIDER_DEFAULTS = "EXTERNAL_PROVIDER_DEFAULTS"
PLUGIN_FIELD_SUPPORTED_MODALITIES = "SUPPORTED_MODALITIES"
PLUGIN_FIELD_CLONABLE_FIELDS = "CLONABLE_FIELDS"
PLUGIN_FIELD_WELCOME_MESSAGE = "WELCOME_MESSAGE"
PLUGIN_FIELD_PLUGIN_DEPENDENCIES = "PLUGIN_DEPENDENCIES"
PLUGIN_FIELD_PACKAGE_DEPENDENCIES = "PACKAGE_DEPENDENCIES"

PLUGIN_REQUIRED_METADATA_FIELDS: tuple[str, ...] = (
    PLUGIN_FIELD_NAME,
    PLUGIN_FIELD_VERSION_SOAIPLUGIN,
    PLUGIN_FIELD_AUTHOR_SOAIPLUGIN,
    PLUGIN_FIELD_DESCRIPTION_SOAIPLUGIN,
    PLUGIN_FIELD_WEBSITE_SOAIPLUGIN,
    PLUGIN_FIELD_WEBSITE_BACKEND,
    PLUGIN_FIELD_LICENSE_SOAIPLUGIN,
    PLUGIN_FIELD_MODEL_REPOSITORY,
    PLUGIN_FIELD_MODEL_TYPES,
    PLUGIN_FIELD_REQUIRED_SOAI_VERSION,
    PLUGIN_FIELD_ALIASES,
    PLUGIN_FIELD_PLUGIN_DEPENDENCIES,
    PLUGIN_FIELD_PACKAGE_DEPENDENCIES,
    PLUGIN_FIELD_SUPPORTED_MODALITIES,
    PLUGIN_FIELD_LOCAL_RESOURCES,
    PLUGIN_FIELD_LOCAL_MODELS,
    PLUGIN_FIELD_PERSISTENT,
    PLUGIN_FIELD_MAX_CONCURRENT_REQUESTS,
    PLUGIN_FIELD_SUPPORTS_BACKEND_INSTALLATION,
    PLUGIN_FIELD_SUPPORTS_BACKEND_PROCESS_TRACKING,
    PLUGIN_FIELD_SUPPORTS_MODEL_DELETION,
    PLUGIN_FIELD_SUPPORTS_MODEL_DOWNLOAD,
    PLUGIN_FIELD_SUPPORTS_CONFIGURATION,
    PLUGIN_FIELD_SUPPORTS_EXTERNAL_PROVIDERS,
    PLUGIN_FIELD_EXTERNAL_PROVIDER_MODE,
    PLUGIN_FIELD_SUPPORTS_CLONING,
    PLUGIN_FIELD_REQUIRED_SYSTEM_CAPABILITIES,
)
