"""SoAI - Shutdown lifecycle budget entry counts [backend/app/lifecycle/shutdown_budget_counts.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = ("SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT",)

PRE_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT = 1
SERVICE_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT = 17
EVENT_BUS_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT = 1
HTTP_CLIENT_AND_DATABASE_COMPONENT_TIMEOUT_ENTRY_COUNT = 4
HARDWARE_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT = 1
SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT = (
    PRE_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT
    + SERVICE_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT
    + EVENT_BUS_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT
    + HTTP_CLIENT_AND_DATABASE_COMPONENT_TIMEOUT_ENTRY_COUNT
    + HARDWARE_SHUTDOWN_COMPONENT_TIMEOUT_ENTRY_COUNT
)
