/* SoAI - Chat page constants shared across controllers [frontend/assets/ts/pages/chat/contracts/constants.ts] */
// SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

const CHAT_DESKTOP_BREAKPOINT_PX = 1200;
const CHAT_COMPOSER_ACTIONS_COLLAPSE_BREAKPOINT_PX = 1024;
const CHAT_SIDEBAR_OVERLAY_BREAKPOINT_PX = 900;
const CHAT_SIDEBAR_TOGGLE_REPOSITION_BREAKPOINT_PX = 900;
const CHAT_AUTOSAVE_INTERVAL_MS = 30_000;

export { CHAT_AUTOSAVE_INTERVAL_MS, CHAT_COMPOSER_ACTIONS_COLLAPSE_BREAKPOINT_PX, CHAT_DESKTOP_BREAKPOINT_PX, CHAT_SIDEBAR_OVERLAY_BREAKPOINT_PX, CHAT_SIDEBAR_TOGGLE_REPOSITION_BREAKPOINT_PX };
