"""SoAI - Semantic timing policy constants [backend/core/timing/constants.py]"""
# SPDX-License-Identifier: LicenseRef-SoAI-Source-1.0

from __future__ import annotations

__all__ = ()

YIELD_CONTROL_SEC = 0.0
TIGHT_POLL_INTERVAL_SEC = 0.01
SHORT_POLL_INTERVAL_SEC = 0.1
FILE_LOCK_RETRY_INTERVAL_SEC = 0.2
ASYNC_POLL_SLICE_SEC = 0.25
MODERATE_DELAY_SEC = 0.5
STANDARD_DELAY_SEC = 1.0

RESPONSIVE_TIMEOUT_SEC = 2
LOCAL_IO_TIMEOUT_SEC = 5
CONTROL_TIMEOUT_SEC = 10
OCR_TIMEOUT_SEC = 15
INTERACTIVE_TIMEOUT_SEC = 30
BACKGROUND_TIMEOUT_SEC = 60
EXTENDED_TIMEOUT_SEC = 120
LONG_REQUEST_TIMEOUT_SEC = 300
SETUP_TIMEOUT_SEC = 600
LONG_IDLE_TIMEOUT_SEC = 3600
